// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetAlttitleByIdOperationResponse is the result of GetAlttitleById.
type GetAlttitleByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *AlternativeTitleResource
}

// GetAlttitleById calls GET /api/v3/alttitle/{id}.
func (c Client) GetAlttitleById(ctx context.Context, id int) (result GetAlttitleByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v3/alttitle/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model AlternativeTitleResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
