// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetAlttitleOperationResponse is the result of GetAlttitle.
type GetAlttitleOperationResponse struct {
	HttpResponse *http.Response
	Model        []AlternativeTitleResource
}

// GetAlttitleOperationOptions holds the query and header parameters of GetAlttitle.
type GetAlttitleOperationOptions struct {
	MovieId         int
	MovieMetadataId int
}

// ToHeaders returns the header parameters the options set.
func (o GetAlttitleOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetAlttitleOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.MovieId != 0 {
		out.Append("movieId", strconv.Itoa(o.MovieId))
	}
	if o.MovieMetadataId != 0 {
		out.Append("movieMetadataId", strconv.Itoa(o.MovieMetadataId))
	}
	return &out
}

// GetAlttitle calls GET /api/v3/alttitle.
func (c Client) GetAlttitle(ctx context.Context, options GetAlttitleOperationOptions) (result GetAlttitleOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/alttitle",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
