// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"net/http"
	"strings"
	"testing"

	"github.com/katbyte/radarr-mcp/lib/client"
)

func TestOperationPostLogin(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "", "")
	result, err := c.PostLogin(t.Context(), strings.NewReader("raw bytes"), "multipart/form-data", PostLoginOperationOptions{
		ReturnUrl: "v-ReturnUrl",
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodPost, "/login")
	expectQuery(t, r, "returnUrl", "v-ReturnUrl")
	if got := r.Header.Get("Content-Type"); got != "multipart/form-data" {
		t.Errorf("Content-Type = %q, want %q", got, "multipart/form-data")
	}
	if body != "raw bytes" {
		t.Errorf("body = %q, want the raw bytes", body)
	}
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.PostLogin(t.Context(), strings.NewReader("raw bytes"), "multipart/form-data", PostLoginOperationOptions{
		ReturnUrl: "v-ReturnUrl",
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
