// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"io"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// PostLoginOperationResponse is the result of PostLogin.
type PostLoginOperationResponse struct {
	HttpResponse *http.Response
}

// PostLoginOperationOptions holds the query and header parameters of PostLogin.
type PostLoginOperationOptions struct {
	ReturnUrl string
}

// ToHeaders returns the header parameters the options set.
func (o PostLoginOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PostLoginOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.ReturnUrl != "" {
		out.Append("returnUrl", o.ReturnUrl)
	}
	return &out
}

// PostLogin calls POST /login.
//
// input is sent as contentType, or as multipart/form-data when that is empty.
func (c Client) PostLogin(ctx context.Context, input io.Reader, contentType string, options PostLoginOperationOptions) (result PostLoginOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "multipart/form-data",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          "/login",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.SetBody(input, contentType); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
