// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetLogoutOperationResponse is the result of GetLogout.
//
// The operation answers text/html, left unread in HttpResponse.Body, which
// the caller must close.
type GetLogoutOperationResponse struct {
	HttpResponse *http.Response
}

// GetLogout calls GET /logout.
func (c Client) GetLogout(ctx context.Context) (result GetLogoutOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:     http.MethodGet,
		Path:           "/logout",
		StreamResponse: true,
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
