// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetAutotaggingSchemaOperationResponse is the result of GetAutotaggingSchema.
type GetAutotaggingSchemaOperationResponse struct {
	HttpResponse *http.Response
	Model        json.RawMessage
}

// GetAutotaggingSchema calls GET /api/v3/autotagging/schema.
func (c Client) GetAutotaggingSchema(ctx context.Context) (result GetAutotaggingSchemaOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/autotagging/schema",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
