// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetBlocklistMovieOperationResponse is the result of GetBlocklistMovie.
type GetBlocklistMovieOperationResponse struct {
	HttpResponse *http.Response
	Model        []BlocklistResource
}

// GetBlocklistMovieOperationOptions holds the query and header parameters of GetBlocklistMovie.
type GetBlocklistMovieOperationOptions struct {
	MovieId int
}

// ToHeaders returns the header parameters the options set.
func (o GetBlocklistMovieOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetBlocklistMovieOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.MovieId != 0 {
		out.Append("movieId", strconv.Itoa(o.MovieId))
	}
	return &out
}

// GetBlocklistMovie calls GET /api/v3/blocklist/movie.
func (c Client) GetBlocklistMovie(ctx context.Context, options GetBlocklistMovieOperationOptions) (result GetBlocklistMovieOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/blocklist/movie",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
