// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// BlocklistResource is the "BlocklistResource" schema.
type BlocklistResource struct {
	CustomFormats []CustomFormatResource `json:"customFormats,omitzero"`
	Date          string                 `json:"date,omitempty"`
	Id            int                    `json:"id,omitempty"`
	Indexer       string                 `json:"indexer,omitempty"`
	Languages     []Language             `json:"languages,omitzero"`
	Message       string                 `json:"message,omitempty"`
	Movie         *MovieResource         `json:"movie,omitempty"`
	MovieId       int                    `json:"movieId,omitempty"`
	Protocol      DownloadProtocol       `json:"protocol,omitempty"`
	Quality       *QualityModel          `json:"quality,omitempty"`
	SourceTitle   string                 `json:"sourceTitle,omitempty"`
}
