// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetFeedV3CalendarRadarrIcsOperationResponse is the result of GetFeedV3CalendarRadarrIcs.
//
// The operation answers text/calendar, left unread in HttpResponse.Body, which
// the caller must close.
type GetFeedV3CalendarRadarrIcsOperationResponse struct {
	HttpResponse *http.Response
}

// GetFeedV3CalendarRadarrIcsOperationOptions holds the query and header parameters of GetFeedV3CalendarRadarrIcs.
type GetFeedV3CalendarRadarrIcsOperationOptions struct {
	PastDays     int
	FutureDays   int
	Tags         string
	Unmonitored  *bool
	ReleaseTypes []CalendarReleaseType
}

// ToHeaders returns the header parameters the options set.
func (o GetFeedV3CalendarRadarrIcsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetFeedV3CalendarRadarrIcsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.PastDays != 0 {
		out.Append("pastDays", strconv.Itoa(o.PastDays))
	}
	if o.FutureDays != 0 {
		out.Append("futureDays", strconv.Itoa(o.FutureDays))
	}
	if o.Tags != "" {
		out.Append("tags", o.Tags)
	}
	if o.Unmonitored != nil {
		out.Append("unmonitored", strconv.FormatBool(*o.Unmonitored))
	}
	for _, v := range o.ReleaseTypes {
		out.Append("releaseTypes", string(v))
	}
	return &out
}

// GetFeedV3CalendarRadarrIcs calls GET /feed/v3/calendar/radarr.ics.
func (c Client) GetFeedV3CalendarRadarrIcs(ctx context.Context, options GetFeedV3CalendarRadarrIcsOperationOptions) (result GetFeedV3CalendarRadarrIcsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:     http.MethodGet,
		OptionsObject:  options,
		Path:           "/feed/v3/calendar/radarr.ics",
		StreamResponse: true,
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
