// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// CalendarReleaseType is the "CalendarReleaseType" enum.
type CalendarReleaseType string

// Values of CalendarReleaseType.
const (
	CalendarReleaseTypeCinemaRelease   CalendarReleaseType = "cinemaRelease"
	CalendarReleaseTypeDigitalRelease  CalendarReleaseType = "digitalRelease"
	CalendarReleaseTypePhysicalRelease CalendarReleaseType = "physicalRelease"
)

// PossibleValuesForCalendarReleaseType returns every value of CalendarReleaseType.
func PossibleValuesForCalendarReleaseType() []string {
	return []string{
		string(CalendarReleaseTypeCinemaRelease),
		string(CalendarReleaseTypeDigitalRelease),
		string(CalendarReleaseTypePhysicalRelease),
	}
}
