// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"io"
	"net/http"
	"testing"

	"github.com/katbyte/radarr-mcp/lib/client"
)

func TestOperationGetFeedV3CalendarRadarrIcs(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "text/calendar", "file bytes")
	result, err := c.GetFeedV3CalendarRadarrIcs(t.Context(), GetFeedV3CalendarRadarrIcsOperationOptions{
		PastDays:     7,
		FutureDays:   7,
		Tags:         "v-Tags",
		Unmonitored:  new(true),
		ReleaseTypes: []CalendarReleaseType{CalendarReleaseTypeCinemaRelease, CalendarReleaseTypePhysicalRelease},
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodGet, "/feed/v3/calendar/radarr.ics")
	expectQuery(t, r, "pastDays", "7")
	expectQuery(t, r, "futureDays", "7")
	expectQuery(t, r, "tags", "v-Tags")
	expectQuery(t, r, "unmonitored", "true")
	expectQuery(t, r, "releaseTypes", "cinemaRelease", "physicalRelease")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}
	streamed, _ := io.ReadAll(result.HttpResponse.Body)
	_ = result.HttpResponse.Body.Close()
	if string(streamed) != "file bytes" {
		t.Errorf("streamed body = %q", streamed)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.GetFeedV3CalendarRadarrIcs(t.Context(), GetFeedV3CalendarRadarrIcsOperationOptions{
		PastDays:     7,
		FutureDays:   7,
		Tags:         "v-Tags",
		Unmonitored:  new(true),
		ReleaseTypes: []CalendarReleaseType{CalendarReleaseTypeCinemaRelease, CalendarReleaseTypePhysicalRelease},
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
