// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"errors"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// Client is a client for the Radarr API; each of its operations is a method.
// Requests go through Client.Client, the shared base client.
type Client struct {
	Client *client.Client
}

// New returns a client for the Radarr server at baseURL (scheme and host,
// plus the URL base when Radarr is set up with one, e.g. /radarr) that
// authenticates with the API key from Settings > General > Security.
func New(baseURL, apiKey string) (*Client, error) {
	if apiKey == "" {
		return nil, errors.New("API key is required")
	}
	c, err := client.New(baseURL, client.APIKey(apiKey))
	if err != nil {
		return nil, err
	}

	return &Client{Client: c}, nil
}
