// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetCollectionOperationResponse is the result of GetCollection.
type GetCollectionOperationResponse struct {
	HttpResponse *http.Response
	Model        []CollectionResource
}

// GetCollectionOperationOptions holds the query and header parameters of GetCollection.
type GetCollectionOperationOptions struct {
	TmdbId int
}

// ToHeaders returns the header parameters the options set.
func (o GetCollectionOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetCollectionOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.TmdbId != 0 {
		out.Append("tmdbId", strconv.Itoa(o.TmdbId))
	}
	return &out
}

// GetCollection calls GET /api/v3/collection.
func (c Client) GetCollection(ctx context.Context, options GetCollectionOperationOptions) (result GetCollectionOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/collection",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
