// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// CollectionResource is the "CollectionResource" schema.
type CollectionResource struct {
	Id                  int                       `json:"id,omitempty"`
	Images              []MediaCover              `json:"images,omitzero"`
	MinimumAvailability MovieStatusType           `json:"minimumAvailability,omitempty"`
	MissingMovies       int                       `json:"missingMovies,omitempty"`
	Monitored           *bool                     `json:"monitored,omitempty"`
	Movies              []CollectionMovieResource `json:"movies,omitzero"`
	Overview            string                    `json:"overview,omitempty"`
	QualityProfileId    int                       `json:"qualityProfileId,omitempty"`
	RootFolderPath      string                    `json:"rootFolderPath,omitempty"`
	SearchOnAdd         *bool                     `json:"searchOnAdd,omitempty"`
	SortTitle           string                    `json:"sortTitle,omitempty"`
	Tags                []int                     `json:"tags,omitzero"`
	Title               string                    `json:"title,omitempty"`
	TmdbId              int                       `json:"tmdbId,omitempty"`
}
