// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// CollectionMovieResource is the "CollectionMovieResource" schema.
type CollectionMovieResource struct {
	CleanTitle string          `json:"cleanTitle,omitempty"`
	Folder     string          `json:"folder,omitempty"`
	Genres     []string        `json:"genres,omitzero"`
	Images     []MediaCover    `json:"images,omitzero"`
	ImdbId     string          `json:"imdbId,omitempty"`
	IsExcluded *bool           `json:"isExcluded,omitempty"`
	IsExisting *bool           `json:"isExisting,omitempty"`
	Overview   string          `json:"overview,omitempty"`
	Ratings    *Ratings        `json:"ratings,omitempty"`
	Runtime    int             `json:"runtime,omitempty"`
	SortTitle  string          `json:"sortTitle,omitempty"`
	Status     MovieStatusType `json:"status,omitempty"`
	Title      string          `json:"title,omitempty"`
	TmdbId     int             `json:"tmdbId,omitempty"`
	Year       int             `json:"year,omitempty"`
}
