// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// PutCollectionByIdOperationResponse is the result of PutCollectionById.
type PutCollectionByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *CollectionResource
}

// PutCollectionById calls PUT /api/v3/collection/{id}.
func (c Client) PutCollectionById(ctx context.Context, id int, input CollectionResource) (result PutCollectionByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusAccepted,
		},
		HttpMethod: http.MethodPut,
		Path:       fmt.Sprintf("/api/v3/collection/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model CollectionResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
