// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// Ratings is the "Ratings" schema.
type Ratings struct {
	Imdb           *RatingChild `json:"imdb,omitempty"`
	Metacritic     *RatingChild `json:"metacritic,omitempty"`
	RottenTomatoes *RatingChild `json:"rottenTomatoes,omitempty"`
	Tmdb           *RatingChild `json:"tmdb,omitempty"`
	Trakt          *RatingChild `json:"trakt,omitempty"`
}
