// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// AlternativeTitleResource is the "AlternativeTitleResource" schema.
type AlternativeTitleResource struct {
	CleanTitle      string     `json:"cleanTitle,omitempty"`
	Id              int        `json:"id,omitempty"`
	MovieMetadataId int        `json:"movieMetadataId,omitempty"`
	SourceType      SourceType `json:"sourceType,omitempty"`
	Title           string     `json:"title,omitempty"`
}
