// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// RatingChild is the "RatingChild" schema.
type RatingChild struct {
	Type  RatingType `json:"type,omitempty"`
	Value float64    `json:"value,omitempty"`
	Votes int        `json:"votes,omitempty"`
}
