// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// MovieResource is the "MovieResource" schema.
type MovieResource struct {
	AddOptions            *AddMovieOptions           `json:"addOptions,omitempty"`
	Added                 string                     `json:"added,omitempty"`
	AlternateTitles       []AlternativeTitleResource `json:"alternateTitles,omitzero"`
	Certification         string                     `json:"certification,omitempty"`
	CleanTitle            string                     `json:"cleanTitle,omitempty"`
	Collection            *MovieCollectionResource   `json:"collection,omitempty"`
	DigitalRelease        string                     `json:"digitalRelease,omitempty"`
	Folder                string                     `json:"folder,omitempty"`
	FolderName            string                     `json:"folderName,omitempty"`
	Genres                []string                   `json:"genres,omitzero"`
	HasFile               *bool                      `json:"hasFile,omitempty"`
	Id                    int                        `json:"id,omitempty"`
	Images                []MediaCover               `json:"images,omitzero"`
	ImdbId                string                     `json:"imdbId,omitempty"`
	InCinemas             string                     `json:"inCinemas,omitempty"`
	IsAvailable           *bool                      `json:"isAvailable,omitempty"`
	IsExcluded            *bool                      `json:"isExcluded,omitempty"`
	Keywords              []string                   `json:"keywords,omitzero"`
	LastSearchTime        string                     `json:"lastSearchTime,omitempty"`
	MinimumAvailability   MovieStatusType            `json:"minimumAvailability,omitempty"`
	Monitored             *bool                      `json:"monitored,omitempty"`
	MovieFile             *MovieFileResource         `json:"movieFile,omitempty"`
	MovieFileId           int                        `json:"movieFileId,omitempty"`
	OriginalLanguage      *Language                  `json:"originalLanguage,omitempty"`
	OriginalTitle         string                     `json:"originalTitle,omitempty"`
	Overview              string                     `json:"overview,omitempty"`
	Path                  string                     `json:"path,omitempty"`
	PhysicalRelease       string                     `json:"physicalRelease,omitempty"`
	PhysicalReleaseNote   string                     `json:"physicalReleaseNote,omitempty"`
	Popularity            float32                    `json:"popularity,omitempty"`
	QualityProfileId      int                        `json:"qualityProfileId,omitempty"`
	Ratings               *Ratings                   `json:"ratings,omitempty"`
	ReleaseDate           string                     `json:"releaseDate,omitempty"`
	RemotePoster          string                     `json:"remotePoster,omitempty"`
	RootFolderPath        string                     `json:"rootFolderPath,omitempty"`
	Runtime               int                        `json:"runtime,omitempty"`
	SecondaryYear         *int                       `json:"secondaryYear,omitempty"`
	SecondaryYearSourceId int                        `json:"secondaryYearSourceId,omitempty"`
	SizeOnDisk            *int64                     `json:"sizeOnDisk,omitempty"`
	SortTitle             string                     `json:"sortTitle,omitempty"`
	Statistics            *MovieStatisticsResource   `json:"statistics,omitempty"`
	Status                MovieStatusType            `json:"status,omitempty"`
	Studio                string                     `json:"studio,omitempty"`
	Tags                  []int                      `json:"tags,omitzero"`
	Title                 string                     `json:"title,omitempty"`
	TitleSlug             string                     `json:"titleSlug,omitempty"`
	TmdbId                int                        `json:"tmdbId,omitempty"`
	Website               string                     `json:"website,omitempty"`
	Year                  int                        `json:"year,omitempty"`
	YouTubeTrailerId      string                     `json:"youTubeTrailerId,omitempty"`
}
