// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// SelectOption is the "SelectOption" schema.
type SelectOption struct {
	DividerAfter *bool  `json:"dividerAfter,omitempty"`
	Hint         string `json:"hint,omitempty"`
	Name         string `json:"name,omitempty"`
	Order        int    `json:"order,omitempty"`
	Value        int    `json:"value,omitempty"`
}
