// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// AddMovieOptions is the "AddMovieOptions" schema.
type AddMovieOptions struct {
	AddMethod                  AddMovieMethod `json:"addMethod,omitempty"`
	IgnoreEpisodesWithFiles    *bool          `json:"ignoreEpisodesWithFiles,omitempty"`
	IgnoreEpisodesWithoutFiles *bool          `json:"ignoreEpisodesWithoutFiles,omitempty"`
	Monitor                    MonitorTypes   `json:"monitor,omitempty"`
	SearchForMovie             *bool          `json:"searchForMovie,omitempty"`
}
