// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// MovieFileResource is the "MovieFileResource" schema.
type MovieFileResource struct {
	CustomFormatScore   *int                   `json:"customFormatScore,omitempty"`
	CustomFormats       []CustomFormatResource `json:"customFormats,omitzero"`
	DateAdded           string                 `json:"dateAdded,omitempty"`
	Edition             string                 `json:"edition,omitempty"`
	Id                  int                    `json:"id,omitempty"`
	IndexerFlags        *int                   `json:"indexerFlags,omitempty"`
	Languages           []Language             `json:"languages,omitzero"`
	MediaInfo           *MediaInfoResource     `json:"mediaInfo,omitempty"`
	MovieId             int                    `json:"movieId,omitempty"`
	OriginalFilePath    string                 `json:"originalFilePath,omitempty"`
	Path                string                 `json:"path,omitempty"`
	Quality             *QualityModel          `json:"quality,omitempty"`
	QualityCutoffNotMet *bool                  `json:"qualityCutoffNotMet,omitempty"`
	RelativePath        string                 `json:"relativePath,omitempty"`
	ReleaseGroup        string                 `json:"releaseGroup,omitempty"`
	SceneName           string                 `json:"sceneName,omitempty"`
	Size                int64                  `json:"size,omitempty"`
}
