// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// MovieStatisticsResource is the "MovieStatisticsResource" schema.
type MovieStatisticsResource struct {
	MovieFileCount     int       `json:"movieFileCount,omitempty"`
	MovieFileQualities []Quality `json:"movieFileQualities,omitzero"`
	ReleaseGroups      []string  `json:"releaseGroups,omitzero"`
	SizeOnDisk         int64     `json:"sizeOnDisk,omitempty"`
}
