// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// ProviderTestAllResult is the "ProviderTestAllResult" schema.
type ProviderTestAllResult struct {
	Id                 int                 `json:"id,omitempty"`
	IsValid            *bool               `json:"isValid,omitempty"`
	ValidationFailures []ValidationFailure `json:"validationFailures,omitzero"`
}
