// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// AddMovieMethod is the "AddMovieMethod" enum.
type AddMovieMethod string

// Values of AddMovieMethod.
const (
	AddMovieMethodManual     AddMovieMethod = "manual"
	AddMovieMethodList       AddMovieMethod = "list"
	AddMovieMethodCollection AddMovieMethod = "collection"
)

// PossibleValuesForAddMovieMethod returns every value of AddMovieMethod.
func PossibleValuesForAddMovieMethod() []string {
	return []string{
		string(AddMovieMethodManual),
		string(AddMovieMethodList),
		string(AddMovieMethodCollection),
	}
}

// ApplyTags is the "ApplyTags" enum.
type ApplyTags string

// Values of ApplyTags.
const (
	ApplyTagsAdd     ApplyTags = "add"
	ApplyTagsRemove  ApplyTags = "remove"
	ApplyTagsReplace ApplyTags = "replace"
)

// PossibleValuesForApplyTags returns every value of ApplyTags.
func PossibleValuesForApplyTags() []string {
	return []string{
		string(ApplyTagsAdd),
		string(ApplyTagsRemove),
		string(ApplyTagsReplace),
	}
}

// AuthenticationType is the "AuthenticationType" enum.
type AuthenticationType string

// Values of AuthenticationType.
const (
	AuthenticationTypeNone     AuthenticationType = "none"
	AuthenticationTypeBasic    AuthenticationType = "basic"
	AuthenticationTypeForms    AuthenticationType = "forms"
	AuthenticationTypeExternal AuthenticationType = "external"
)

// PossibleValuesForAuthenticationType returns every value of AuthenticationType.
func PossibleValuesForAuthenticationType() []string {
	return []string{
		string(AuthenticationTypeNone),
		string(AuthenticationTypeBasic),
		string(AuthenticationTypeForms),
		string(AuthenticationTypeExternal),
	}
}

// DownloadProtocol is the "DownloadProtocol" enum.
type DownloadProtocol string

// Values of DownloadProtocol.
const (
	DownloadProtocolUnknown DownloadProtocol = "unknown"
	DownloadProtocolUsenet  DownloadProtocol = "usenet"
	DownloadProtocolTorrent DownloadProtocol = "torrent"
)

// PossibleValuesForDownloadProtocol returns every value of DownloadProtocol.
func PossibleValuesForDownloadProtocol() []string {
	return []string{
		string(DownloadProtocolUnknown),
		string(DownloadProtocolUsenet),
		string(DownloadProtocolTorrent),
	}
}

// MediaCoverTypes is the "MediaCoverTypes" enum.
type MediaCoverTypes string

// Values of MediaCoverTypes.
const (
	MediaCoverTypesUnknown    MediaCoverTypes = "unknown"
	MediaCoverTypesPoster     MediaCoverTypes = "poster"
	MediaCoverTypesBanner     MediaCoverTypes = "banner"
	MediaCoverTypesFanart     MediaCoverTypes = "fanart"
	MediaCoverTypesScreenshot MediaCoverTypes = "screenshot"
	MediaCoverTypesHeadshot   MediaCoverTypes = "headshot"
	MediaCoverTypesClearlogo  MediaCoverTypes = "clearlogo"
)

// PossibleValuesForMediaCoverTypes returns every value of MediaCoverTypes.
func PossibleValuesForMediaCoverTypes() []string {
	return []string{
		string(MediaCoverTypesUnknown),
		string(MediaCoverTypesPoster),
		string(MediaCoverTypesBanner),
		string(MediaCoverTypesFanart),
		string(MediaCoverTypesScreenshot),
		string(MediaCoverTypesHeadshot),
		string(MediaCoverTypesClearlogo),
	}
}

// Modifier is the "Modifier" enum.
type Modifier string

// Values of Modifier.
const (
	ModifierNone     Modifier = "none"
	ModifierRegional Modifier = "regional"
	ModifierScreener Modifier = "screener"
	ModifierRawhd    Modifier = "rawhd"
	ModifierBrdisk   Modifier = "brdisk"
	ModifierRemux    Modifier = "remux"
)

// PossibleValuesForModifier returns every value of Modifier.
func PossibleValuesForModifier() []string {
	return []string{
		string(ModifierNone),
		string(ModifierRegional),
		string(ModifierScreener),
		string(ModifierRawhd),
		string(ModifierBrdisk),
		string(ModifierRemux),
	}
}

// MonitorTypes is the "MonitorTypes" enum.
type MonitorTypes string

// Values of MonitorTypes.
const (
	MonitorTypesMovieOnly          MonitorTypes = "movieOnly"
	MonitorTypesMovieAndCollection MonitorTypes = "movieAndCollection"
	MonitorTypesNone               MonitorTypes = "none"
)

// PossibleValuesForMonitorTypes returns every value of MonitorTypes.
func PossibleValuesForMonitorTypes() []string {
	return []string{
		string(MonitorTypesMovieOnly),
		string(MonitorTypesMovieAndCollection),
		string(MonitorTypesNone),
	}
}

// MovieStatusType is the "MovieStatusType" enum.
type MovieStatusType string

// Values of MovieStatusType.
const (
	MovieStatusTypeTba       MovieStatusType = "tba"
	MovieStatusTypeAnnounced MovieStatusType = "announced"
	MovieStatusTypeInCinemas MovieStatusType = "inCinemas"
	MovieStatusTypeReleased  MovieStatusType = "released"
	MovieStatusTypeDeleted   MovieStatusType = "deleted"
)

// PossibleValuesForMovieStatusType returns every value of MovieStatusType.
func PossibleValuesForMovieStatusType() []string {
	return []string{
		string(MovieStatusTypeTba),
		string(MovieStatusTypeAnnounced),
		string(MovieStatusTypeInCinemas),
		string(MovieStatusTypeReleased),
		string(MovieStatusTypeDeleted),
	}
}

// PrivacyLevel is the "PrivacyLevel" enum.
type PrivacyLevel string

// Values of PrivacyLevel.
const (
	PrivacyLevelNormal   PrivacyLevel = "normal"
	PrivacyLevelPassword PrivacyLevel = "password"
	PrivacyLevelApiKey   PrivacyLevel = "apiKey"
	PrivacyLevelUserName PrivacyLevel = "userName"
)

// PossibleValuesForPrivacyLevel returns every value of PrivacyLevel.
func PossibleValuesForPrivacyLevel() []string {
	return []string{
		string(PrivacyLevelNormal),
		string(PrivacyLevelPassword),
		string(PrivacyLevelApiKey),
		string(PrivacyLevelUserName),
	}
}

// ProviderMessageType is the "ProviderMessageType" enum.
type ProviderMessageType string

// Values of ProviderMessageType.
const (
	ProviderMessageTypeInfo    ProviderMessageType = "info"
	ProviderMessageTypeWarning ProviderMessageType = "warning"
	ProviderMessageTypeError   ProviderMessageType = "error"
)

// PossibleValuesForProviderMessageType returns every value of ProviderMessageType.
func PossibleValuesForProviderMessageType() []string {
	return []string{
		string(ProviderMessageTypeInfo),
		string(ProviderMessageTypeWarning),
		string(ProviderMessageTypeError),
	}
}

// QualitySource is the "QualitySource" enum.
type QualitySource string

// Values of QualitySource.
const (
	QualitySourceUnknown   QualitySource = "unknown"
	QualitySourceCam       QualitySource = "cam"
	QualitySourceTelesync  QualitySource = "telesync"
	QualitySourceTelecine  QualitySource = "telecine"
	QualitySourceWorkprint QualitySource = "workprint"
	QualitySourceDvd       QualitySource = "dvd"
	QualitySourceTv        QualitySource = "tv"
	QualitySourceWebdl     QualitySource = "webdl"
	QualitySourceWebrip    QualitySource = "webrip"
	QualitySourceBluray    QualitySource = "bluray"
)

// PossibleValuesForQualitySource returns every value of QualitySource.
func PossibleValuesForQualitySource() []string {
	return []string{
		string(QualitySourceUnknown),
		string(QualitySourceCam),
		string(QualitySourceTelesync),
		string(QualitySourceTelecine),
		string(QualitySourceWorkprint),
		string(QualitySourceDvd),
		string(QualitySourceTv),
		string(QualitySourceWebdl),
		string(QualitySourceWebrip),
		string(QualitySourceBluray),
	}
}

// QueueStatus is the "QueueStatus" enum.
type QueueStatus string

// Values of QueueStatus.
const (
	QueueStatusUnknown                   QueueStatus = "unknown"
	QueueStatusQueued                    QueueStatus = "queued"
	QueueStatusPaused                    QueueStatus = "paused"
	QueueStatusDownloading               QueueStatus = "downloading"
	QueueStatusCompleted                 QueueStatus = "completed"
	QueueStatusFailed                    QueueStatus = "failed"
	QueueStatusWarning                   QueueStatus = "warning"
	QueueStatusDelay                     QueueStatus = "delay"
	QueueStatusDownloadClientUnavailable QueueStatus = "downloadClientUnavailable"
	QueueStatusFallback                  QueueStatus = "fallback"
)

// PossibleValuesForQueueStatus returns every value of QueueStatus.
func PossibleValuesForQueueStatus() []string {
	return []string{
		string(QueueStatusUnknown),
		string(QueueStatusQueued),
		string(QueueStatusPaused),
		string(QueueStatusDownloading),
		string(QueueStatusCompleted),
		string(QueueStatusFailed),
		string(QueueStatusWarning),
		string(QueueStatusDelay),
		string(QueueStatusDownloadClientUnavailable),
		string(QueueStatusFallback),
	}
}

// RatingType is the "RatingType" enum.
type RatingType string

// Values of RatingType.
const (
	RatingTypeUser   RatingType = "user"
	RatingTypeCritic RatingType = "critic"
)

// PossibleValuesForRatingType returns every value of RatingType.
func PossibleValuesForRatingType() []string {
	return []string{
		string(RatingTypeUser),
		string(RatingTypeCritic),
	}
}

// SortDirection is the "SortDirection" enum.
type SortDirection string

// Values of SortDirection.
const (
	SortDirectionDefault    SortDirection = "default"
	SortDirectionAscending  SortDirection = "ascending"
	SortDirectionDescending SortDirection = "descending"
)

// PossibleValuesForSortDirection returns every value of SortDirection.
func PossibleValuesForSortDirection() []string {
	return []string{
		string(SortDirectionDefault),
		string(SortDirectionAscending),
		string(SortDirectionDescending),
	}
}

// SourceType is the "SourceType" enum.
type SourceType string

// Values of SourceType.
const (
	SourceTypeTmdb     SourceType = "tmdb"
	SourceTypeMappings SourceType = "mappings"
	SourceTypeUser     SourceType = "user"
	SourceTypeIndexer  SourceType = "indexer"
)

// PossibleValuesForSourceType returns every value of SourceType.
func PossibleValuesForSourceType() []string {
	return []string{
		string(SourceTypeTmdb),
		string(SourceTypeMappings),
		string(SourceTypeUser),
		string(SourceTypeIndexer),
	}
}

// TrackedDownloadState is the "TrackedDownloadState" enum.
type TrackedDownloadState string

// Values of TrackedDownloadState.
const (
	TrackedDownloadStateDownloading   TrackedDownloadState = "downloading"
	TrackedDownloadStateImportBlocked TrackedDownloadState = "importBlocked"
	TrackedDownloadStateImportPending TrackedDownloadState = "importPending"
	TrackedDownloadStateImporting     TrackedDownloadState = "importing"
	TrackedDownloadStateImported      TrackedDownloadState = "imported"
	TrackedDownloadStateFailedPending TrackedDownloadState = "failedPending"
	TrackedDownloadStateFailed        TrackedDownloadState = "failed"
	TrackedDownloadStateIgnored       TrackedDownloadState = "ignored"
)

// PossibleValuesForTrackedDownloadState returns every value of TrackedDownloadState.
func PossibleValuesForTrackedDownloadState() []string {
	return []string{
		string(TrackedDownloadStateDownloading),
		string(TrackedDownloadStateImportBlocked),
		string(TrackedDownloadStateImportPending),
		string(TrackedDownloadStateImporting),
		string(TrackedDownloadStateImported),
		string(TrackedDownloadStateFailedPending),
		string(TrackedDownloadStateFailed),
		string(TrackedDownloadStateIgnored),
	}
}

// TrackedDownloadStatus is the "TrackedDownloadStatus" enum.
type TrackedDownloadStatus string

// Values of TrackedDownloadStatus.
const (
	TrackedDownloadStatusOk      TrackedDownloadStatus = "ok"
	TrackedDownloadStatusWarning TrackedDownloadStatus = "warning"
	TrackedDownloadStatusError   TrackedDownloadStatus = "error"
)

// PossibleValuesForTrackedDownloadStatus returns every value of TrackedDownloadStatus.
func PossibleValuesForTrackedDownloadStatus() []string {
	return []string{
		string(TrackedDownloadStatusOk),
		string(TrackedDownloadStatusWarning),
		string(TrackedDownloadStatusError),
	}
}

// UpdateMechanism is the "UpdateMechanism" enum.
type UpdateMechanism string

// Values of UpdateMechanism.
const (
	UpdateMechanismBuiltIn  UpdateMechanism = "builtIn"
	UpdateMechanismScript   UpdateMechanism = "script"
	UpdateMechanismExternal UpdateMechanism = "external"
	UpdateMechanismApt      UpdateMechanism = "apt"
	UpdateMechanismDocker   UpdateMechanism = "docker"
)

// PossibleValuesForUpdateMechanism returns every value of UpdateMechanism.
func PossibleValuesForUpdateMechanism() []string {
	return []string{
		string(UpdateMechanismBuiltIn),
		string(UpdateMechanismScript),
		string(UpdateMechanismExternal),
		string(UpdateMechanismApt),
		string(UpdateMechanismDocker),
	}
}
