// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// QueueResource is the "QueueResource" schema.
type QueueResource struct {
	Added                               string                         `json:"added,omitempty"`
	CustomFormatScore                   int                            `json:"customFormatScore,omitempty"`
	CustomFormats                       []CustomFormatResource         `json:"customFormats,omitzero"`
	DownloadClient                      string                         `json:"downloadClient,omitempty"`
	DownloadClientHasPostImportCategory *bool                          `json:"downloadClientHasPostImportCategory,omitempty"`
	DownloadId                          string                         `json:"downloadId,omitempty"`
	ErrorMessage                        string                         `json:"errorMessage,omitempty"`
	EstimatedCompletionTime             string                         `json:"estimatedCompletionTime,omitempty"`
	Id                                  int                            `json:"id,omitempty"`
	Indexer                             string                         `json:"indexer,omitempty"`
	Languages                           []Language                     `json:"languages,omitzero"`
	Movie                               *MovieResource                 `json:"movie,omitempty"`
	MovieId                             *int                           `json:"movieId,omitempty"`
	OutputPath                          string                         `json:"outputPath,omitempty"`
	Protocol                            DownloadProtocol               `json:"protocol,omitempty"`
	Quality                             *QualityModel                  `json:"quality,omitempty"`
	Size                                float64                        `json:"size,omitempty"`
	Sizeleft                            float64                        `json:"sizeleft,omitempty"`
	Status                              QueueStatus                    `json:"status,omitempty"`
	StatusMessages                      []TrackedDownloadStatusMessage `json:"statusMessages,omitzero"`
	Timeleft                            string                         `json:"timeleft,omitempty"`
	Title                               string                         `json:"title,omitempty"`
	TrackedDownloadState                TrackedDownloadState           `json:"trackedDownloadState,omitempty"`
	TrackedDownloadStatus               TrackedDownloadStatus          `json:"trackedDownloadStatus,omitempty"`
}
