// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// ReleaseResource is the "ReleaseResource" schema.
type ReleaseResource struct {
	Age                 int                    `json:"age,omitempty"`
	AgeHours            float64                `json:"ageHours,omitempty"`
	AgeMinutes          float64                `json:"ageMinutes,omitempty"`
	Approved            *bool                  `json:"approved,omitempty"`
	CommentUrl          string                 `json:"commentUrl,omitempty"`
	CustomFormatScore   int                    `json:"customFormatScore,omitempty"`
	CustomFormats       []CustomFormatResource `json:"customFormats,omitzero"`
	DownloadAllowed     *bool                  `json:"downloadAllowed,omitempty"`
	DownloadClient      string                 `json:"downloadClient,omitempty"`
	DownloadClientId    *int                   `json:"downloadClientId,omitempty"`
	DownloadUrl         string                 `json:"downloadUrl,omitempty"`
	Edition             string                 `json:"edition,omitempty"`
	Guid                string                 `json:"guid,omitempty"`
	Id                  int                    `json:"id,omitempty"`
	ImdbId              int                    `json:"imdbId,omitempty"`
	Indexer             string                 `json:"indexer,omitempty"`
	IndexerFlags        any                    `json:"indexerFlags,omitempty"`
	IndexerId           int                    `json:"indexerId,omitempty"`
	InfoHash            string                 `json:"infoHash,omitempty"`
	InfoUrl             string                 `json:"infoUrl,omitempty"`
	Languages           []Language             `json:"languages,omitzero"`
	Leechers            *int                   `json:"leechers,omitempty"`
	MagnetUrl           string                 `json:"magnetUrl,omitempty"`
	MappedMovieId       *int                   `json:"mappedMovieId,omitempty"`
	MovieId             *int                   `json:"movieId,omitempty"`
	MovieRequested      *bool                  `json:"movieRequested,omitempty"`
	MovieTitles         []string               `json:"movieTitles,omitzero"`
	Protocol            DownloadProtocol       `json:"protocol,omitempty"`
	PublishDate         string                 `json:"publishDate,omitempty"`
	Quality             *QualityModel          `json:"quality,omitempty"`
	QualityWeight       int                    `json:"qualityWeight,omitempty"`
	Rejected            *bool                  `json:"rejected,omitempty"`
	Rejections          []string               `json:"rejections,omitzero"`
	ReleaseGroup        string                 `json:"releaseGroup,omitempty"`
	ReleaseHash         string                 `json:"releaseHash,omitempty"`
	ReleaseWeight       int                    `json:"releaseWeight,omitempty"`
	SceneSource         *bool                  `json:"sceneSource,omitempty"`
	Seeders             *int                   `json:"seeders,omitempty"`
	ShouldOverride      *bool                  `json:"shouldOverride,omitempty"`
	Size                int64                  `json:"size,omitempty"`
	SubGroup            string                 `json:"subGroup,omitempty"`
	TemporarilyRejected *bool                  `json:"temporarilyRejected,omitempty"`
	Title               string                 `json:"title,omitempty"`
	TmdbId              int                    `json:"tmdbId,omitempty"`
}
