// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// MovieResourcePagingResource is the "MovieResourcePagingResource" schema.
type MovieResourcePagingResource struct {
	Page          int             `json:"page,omitempty"`
	PageSize      int             `json:"pageSize,omitempty"`
	Records       []MovieResource `json:"records,omitzero"`
	SortDirection SortDirection   `json:"sortDirection,omitempty"`
	SortKey       string          `json:"sortKey,omitempty"`
	TotalRecords  int             `json:"totalRecords,omitempty"`
}
