// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// ValidationFailure is the "ValidationFailure" schema.
type ValidationFailure struct {
	DetailedDescription string `json:"detailedDescription,omitempty"`
	ErrorMessage        string `json:"errorMessage,omitempty"`
	InfoLink            string `json:"infoLink,omitempty"`
	IsWarning           *bool  `json:"isWarning,omitempty"`
	PropertyName        string `json:"propertyName,omitempty"`

	// error, warning or info
	Severity string `json:"severity,omitempty"`
}
