// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// ProfileFormatItemResource is the "ProfileFormatItemResource" schema.
type ProfileFormatItemResource struct {
	Format int    `json:"format,omitempty"`
	Id     int    `json:"id,omitempty"`
	Name   string `json:"name,omitempty"`
	Score  int    `json:"score,omitempty"`
}
