// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// MovieCollectionResource is the "MovieCollectionResource" schema.
type MovieCollectionResource struct {
	Title  string `json:"title,omitempty"`
	TmdbId int    `json:"tmdbId,omitempty"`
}
