// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// Quality is the "Quality" schema.
type Quality struct {
	Id         int           `json:"id,omitempty"`
	Modifier   Modifier      `json:"modifier,omitempty"`
	Name       string        `json:"name,omitempty"`
	Resolution int           `json:"resolution,omitempty"`
	Source     QualitySource `json:"source,omitempty"`
}
