// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// CreditResource is the "CreditResource" schema.
type CreditResource struct {
	Character       string       `json:"character,omitempty"`
	CreditTmdbId    string       `json:"creditTmdbId,omitempty"`
	Department      string       `json:"department,omitempty"`
	Id              int          `json:"id,omitempty"`
	Images          []MediaCover `json:"images,omitzero"`
	Job             string       `json:"job,omitempty"`
	MovieMetadataId int          `json:"movieMetadataId,omitempty"`
	Order           int          `json:"order,omitempty"`
	PersonName      string       `json:"personName,omitempty"`
	PersonTmdbId    int          `json:"personTmdbId,omitempty"`
	Type            CreditType   `json:"type,omitempty"`
}
