// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// CreditType is the "CreditType" enum.
type CreditType string

// Values of CreditType.
const (
	CreditTypeCast CreditType = "cast"
	CreditTypeCrew CreditType = "crew"
)

// PossibleValuesForCreditType returns every value of CreditType.
func PossibleValuesForCreditType() []string {
	return []string{
		string(CreditTypeCast),
		string(CreditTypeCrew),
	}
}
