// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetCreditOperationResponse is the result of GetCredit.
type GetCreditOperationResponse struct {
	HttpResponse *http.Response
	Model        []CreditResource
}

// GetCreditOperationOptions holds the query and header parameters of GetCredit.
type GetCreditOperationOptions struct {
	MovieId         int
	MovieMetadataId int
}

// ToHeaders returns the header parameters the options set.
func (o GetCreditOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetCreditOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.MovieId != 0 {
		out.Append("movieId", strconv.Itoa(o.MovieId))
	}
	if o.MovieMetadataId != 0 {
		out.Append("movieMetadataId", strconv.Itoa(o.MovieMetadataId))
	}
	return &out
}

// GetCredit calls GET /api/v3/credit.
func (c Client) GetCredit(ctx context.Context, options GetCreditOperationOptions) (result GetCreditOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/credit",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
