// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// PutCustomformatBulkOperationResponse is the result of PutCustomformatBulk.
type PutCustomformatBulkOperationResponse struct {
	HttpResponse *http.Response
	Model        []CustomFormatResource
}

// PutCustomformatBulk calls PUT /api/v3/customformat/bulk.
func (c Client) PutCustomformatBulk(ctx context.Context, input CustomFormatBulkResource) (result PutCustomformatBulkOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusAccepted,
		},
		HttpMethod: http.MethodPut,
		Path:       "/api/v3/customformat/bulk",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
