// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetCustomformatSchemaOperationResponse is the result of GetCustomformatSchema.
type GetCustomformatSchemaOperationResponse struct {
	HttpResponse *http.Response
	Model        json.RawMessage
}

// GetCustomformatSchema calls GET /api/v3/customformat/schema.
func (c Client) GetCustomformatSchema(ctx context.Context) (result GetCustomformatSchemaOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/customformat/schema",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
