// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// PostCustomfilterOperationResponse is the result of PostCustomfilter.
type PostCustomfilterOperationResponse struct {
	HttpResponse *http.Response
	Model        *CustomFilterResource
}

// PostCustomfilter calls POST /api/v3/customfilter.
func (c Client) PostCustomfilter(ctx context.Context, input CustomFilterResource) (result PostCustomfilterOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusCreated,
		},
		HttpMethod: http.MethodPost,
		Path:       "/api/v3/customfilter",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model CustomFilterResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
