// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetDelayprofileOperationResponse is the result of GetDelayprofile.
type GetDelayprofileOperationResponse struct {
	HttpResponse *http.Response
	Model        []DelayProfileResource
}

// GetDelayprofile calls GET /api/v3/delayprofile.
func (c Client) GetDelayprofile(ctx context.Context) (result GetDelayprofileOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/delayprofile",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
