// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// PutDelayprofileReorderByIdOperationResponse is the result of PutDelayprofileReorderById.
type PutDelayprofileReorderByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        []DelayProfileResource
}

// PutDelayprofileReorderByIdOperationOptions holds the query and header parameters of PutDelayprofileReorderById.
type PutDelayprofileReorderByIdOperationOptions struct {
	After int
}

// ToHeaders returns the header parameters the options set.
func (o PutDelayprofileReorderByIdOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PutDelayprofileReorderByIdOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.After != 0 {
		out.Append("after", strconv.Itoa(o.After))
	}
	return &out
}

// PutDelayprofileReorderById calls PUT /api/v3/delayprofile/reorder/{id}.
func (c Client) PutDelayprofileReorderById(ctx context.Context, id int, options PutDelayprofileReorderByIdOperationOptions) (result PutDelayprofileReorderByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodPut,
		OptionsObject: options,
		Path:          fmt.Sprintf("/api/v3/delayprofile/reorder/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
