// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetDelayprofileByIdOperationResponse is the result of GetDelayprofileById.
type GetDelayprofileByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *DelayProfileResource
}

// GetDelayprofileById calls GET /api/v3/delayprofile/{id}.
func (c Client) GetDelayprofileById(ctx context.Context, id int) (result GetDelayprofileByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v3/delayprofile/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model DelayProfileResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
