// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// PutDelayprofileByIdOperationResponse is the result of PutDelayprofileById.
type PutDelayprofileByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *DelayProfileResource
}

// PutDelayprofileById calls PUT /api/v3/delayprofile/{id}.
func (c Client) PutDelayprofileById(ctx context.Context, id int, input DelayProfileResource) (result PutDelayprofileByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusAccepted,
		},
		HttpMethod: http.MethodPut,
		Path:       fmt.Sprintf("/api/v3/delayprofile/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model DelayProfileResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
