// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetDiskspaceOperationResponse is the result of GetDiskspace.
type GetDiskspaceOperationResponse struct {
	HttpResponse *http.Response
	Model        []DiskSpaceResource
}

// GetDiskspace calls GET /api/v3/diskspace.
func (c Client) GetDiskspace(ctx context.Context) (result GetDiskspaceOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/diskspace",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
