// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetDownloadclientOperationResponse is the result of GetDownloadclient.
type GetDownloadclientOperationResponse struct {
	HttpResponse *http.Response
	Model        []DownloadClientResource
}

// GetDownloadclient calls GET /api/v3/downloadclient.
func (c Client) GetDownloadclient(ctx context.Context) (result GetDownloadclientOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/downloadclient",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
