// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// PostDownloadclientActionByNameOperationResponse is the result of PostDownloadclientActionByName.
type PostDownloadclientActionByNameOperationResponse struct {
	HttpResponse *http.Response
	Model        json.RawMessage
}

// PostDownloadclientActionByName calls POST /api/v3/downloadclient/action/{name}.
func (c Client) PostDownloadclientActionByName(ctx context.Context, name string, input DownloadClientResource) (result PostDownloadclientActionByNameOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodPost,
		Path:       fmt.Sprintf("/api/v3/downloadclient/action/%s", url.PathEscape(name)),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
