// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// PostDownloadclientTestallOperationResponse is the result of PostDownloadclientTestall.
type PostDownloadclientTestallOperationResponse struct {
	HttpResponse *http.Response
	Model        []ProviderTestAllResult
}

// PostDownloadclientTestall calls POST /api/v3/downloadclient/testall.
func (c Client) PostDownloadclientTestall(ctx context.Context) (result PostDownloadclientTestallOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodPost,
		Path:       "/api/v3/downloadclient/testall",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
