// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetConfigDownloadclientOperationResponse is the result of GetConfigDownloadclient.
type GetConfigDownloadclientOperationResponse struct {
	HttpResponse *http.Response
	Model        *DownloadClientConfigResource
}

// GetConfigDownloadclient calls GET /api/v3/config/downloadclient.
func (c Client) GetConfigDownloadclient(ctx context.Context) (result GetConfigDownloadclientOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/config/downloadclient",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model DownloadClientConfigResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
