// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// DownloadClientConfigResource is the "DownloadClientConfigResource" schema.
type DownloadClientConfigResource struct {
	AutoRedownloadFailed                      *bool  `json:"autoRedownloadFailed,omitempty"`
	AutoRedownloadFailedFromInteractiveSearch *bool  `json:"autoRedownloadFailedFromInteractiveSearch,omitempty"`
	CheckForFinishedDownloadInterval          int    `json:"checkForFinishedDownloadInterval,omitempty"`
	DownloadClientWorkingFolders              string `json:"downloadClientWorkingFolders,omitempty"`
	EnableCompletedDownloadHandling           *bool  `json:"enableCompletedDownloadHandling,omitempty"`
	Id                                        int    `json:"id,omitempty"`
}
