// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// PutConfigDownloadclientByIdOperationResponse is the result of PutConfigDownloadclientById.
type PutConfigDownloadclientByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *DownloadClientConfigResource
}

// PutConfigDownloadclientById calls PUT /api/v3/config/downloadclient/{id}.
func (c Client) PutConfigDownloadclientById(ctx context.Context, id int, input DownloadClientConfigResource) (result PutConfigDownloadclientByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusAccepted,
		},
		HttpMethod: http.MethodPut,
		Path:       fmt.Sprintf("/api/v3/config/downloadclient/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model DownloadClientConfigResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
