// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetExtrafileOperationResponse is the result of GetExtrafile.
type GetExtrafileOperationResponse struct {
	HttpResponse *http.Response
	Model        []ExtraFileResource
}

// GetExtrafileOperationOptions holds the query and header parameters of GetExtrafile.
type GetExtrafileOperationOptions struct {
	MovieId int
}

// ToHeaders returns the header parameters the options set.
func (o GetExtrafileOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetExtrafileOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.MovieId != 0 {
		out.Append("movieId", strconv.Itoa(o.MovieId))
	}
	return &out
}

// GetExtrafile calls GET /api/v3/extrafile.
func (c Client) GetExtrafile(ctx context.Context, options GetExtrafileOperationOptions) (result GetExtrafileOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/extrafile",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
