// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// ExtraFileType is the "ExtraFileType" enum.
type ExtraFileType string

// Values of ExtraFileType.
const (
	ExtraFileTypeSubtitle ExtraFileType = "subtitle"
	ExtraFileTypeMetadata ExtraFileType = "metadata"
	ExtraFileTypeOther    ExtraFileType = "other"
)

// PossibleValuesForExtraFileType returns every value of ExtraFileType.
func PossibleValuesForExtraFileType() []string {
	return []string{
		string(ExtraFileTypeSubtitle),
		string(ExtraFileTypeMetadata),
		string(ExtraFileTypeOther),
	}
}
