// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetFilesystemTypeOperationResponse is the result of GetFilesystemType.
type GetFilesystemTypeOperationResponse struct {
	HttpResponse *http.Response
	Model        json.RawMessage
}

// GetFilesystemTypeOperationOptions holds the query and header parameters of GetFilesystemType.
type GetFilesystemTypeOperationOptions struct {
	Path string
}

// ToHeaders returns the header parameters the options set.
func (o GetFilesystemTypeOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetFilesystemTypeOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Path != "" {
		out.Append("path", o.Path)
	}
	return &out
}

// GetFilesystemType calls GET /api/v3/filesystem/type.
func (c Client) GetFilesystemType(ctx context.Context, options GetFilesystemTypeOperationOptions) (result GetFilesystemTypeOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/filesystem/type",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
