// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// HistoryResource is the "HistoryResource" schema.
type HistoryResource struct {
	CustomFormatScore   int                    `json:"customFormatScore,omitempty"`
	CustomFormats       []CustomFormatResource `json:"customFormats,omitzero"`
	Data                map[string]string      `json:"data,omitzero"`
	Date                string                 `json:"date,omitempty"`
	DownloadId          string                 `json:"downloadId,omitempty"`
	EventType           MovieHistoryEventType  `json:"eventType,omitempty"`
	Id                  int                    `json:"id,omitempty"`
	Languages           []Language             `json:"languages,omitzero"`
	Movie               *MovieResource         `json:"movie,omitempty"`
	MovieId             int                    `json:"movieId,omitempty"`
	Quality             *QualityModel          `json:"quality,omitempty"`
	QualityCutoffNotMet *bool                  `json:"qualityCutoffNotMet,omitempty"`
	SourceTitle         string                 `json:"sourceTitle,omitempty"`
}
