// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"net/http"
	"slices"
	"testing"

	"github.com/katbyte/radarr-mcp/lib/client"
)

func TestOperationGetHistory(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "application/json", "{}")
	result, err := c.GetHistory(t.Context(), GetHistoryOperationOptions{
		Page:          7,
		PageSize:      7,
		SortKey:       "v-SortKey",
		SortDirection: SortDirectionDefault,
		IncludeMovie:  new(true),
		EventType:     []int{1, 2},
		DownloadId:    "v-DownloadId",
		MovieIds:      []int{1, 2},
		Languages:     []int{1, 2},
		Quality:       []int{1, 2},
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodGet, "/api/v3/history")
	expectQuery(t, r, "page", "7")
	expectQuery(t, r, "pageSize", "7")
	expectQuery(t, r, "sortKey", "v-SortKey")
	expectQuery(t, r, "sortDirection", "default")
	expectQuery(t, r, "includeMovie", "true")
	expectQuery(t, r, "eventType", "1", "2")
	expectQuery(t, r, "downloadId", "v-DownloadId")
	expectQuery(t, r, "movieIds", "1", "2")
	expectQuery(t, r, "languages", "1", "2")
	expectQuery(t, r, "quality", "1", "2")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}
	if result.Model == nil {
		t.Error("the model was not decoded")
	}

	// an answer that does not decode is an error, with the response
	c, _ = newOperationServer(t, 200, "application/json", "<html>")
	result, err = c.GetHistory(t.Context(), GetHistoryOperationOptions{
		Page:          7,
		PageSize:      7,
		SortKey:       "v-SortKey",
		SortDirection: SortDirectionDefault,
		IncludeMovie:  new(true),
		EventType:     []int{1, 2},
		DownloadId:    "v-DownloadId",
		MovieIds:      []int{1, 2},
		Languages:     []int{1, 2},
		Quality:       []int{1, 2},
	})
	if err == nil || client.StatusCode(err) != 0 || result.HttpResponse == nil {
		t.Errorf("an answer that does not decode = %v", err)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.GetHistory(t.Context(), GetHistoryOperationOptions{
		Page:          7,
		PageSize:      7,
		SortKey:       "v-SortKey",
		SortDirection: SortDirectionDefault,
		IncludeMovie:  new(true),
		EventType:     []int{1, 2},
		DownloadId:    "v-DownloadId",
		MovieIds:      []int{1, 2},
		Languages:     []int{1, 2},
		Quality:       []int{1, 2},
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}

func TestOperationGetHistoryComplete(t *testing.T) {
	t.Parallel()

	c, pages := pagedServer(t, "page", "{}", 2)
	result, err := c.GetHistoryComplete(t.Context(), GetHistoryOperationOptions{PageSize: 1})
	if err != nil {
		t.Fatal(err)
	}
	// a page of one from the first page, then the second, then the total is reached
	if len(result.Items) != 2 || !slices.Equal(*pages, []string{"1", "2"}) || result.LatestHttpResponse == nil {
		t.Errorf("Complete = %d items over pages %q", len(result.Items), *pages)
	}
}
