// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetHistoryMovieOperationResponse is the result of GetHistoryMovie.
type GetHistoryMovieOperationResponse struct {
	HttpResponse *http.Response
	Model        []HistoryResource
}

// GetHistoryMovieOperationOptions holds the query and header parameters of GetHistoryMovie.
type GetHistoryMovieOperationOptions struct {
	MovieId      int
	EventType    MovieHistoryEventType
	IncludeMovie *bool
}

// ToHeaders returns the header parameters the options set.
func (o GetHistoryMovieOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetHistoryMovieOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.MovieId != 0 {
		out.Append("movieId", strconv.Itoa(o.MovieId))
	}
	if o.EventType != "" {
		out.Append("eventType", string(o.EventType))
	}
	if o.IncludeMovie != nil {
		out.Append("includeMovie", strconv.FormatBool(*o.IncludeMovie))
	}
	return &out
}

// GetHistoryMovie calls GET /api/v3/history/movie.
func (c Client) GetHistoryMovie(ctx context.Context, options GetHistoryMovieOperationOptions) (result GetHistoryMovieOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/history/movie",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
