// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// MovieHistoryEventType is the "MovieHistoryEventType" enum.
type MovieHistoryEventType string

// Values of MovieHistoryEventType.
const (
	MovieHistoryEventTypeUnknown                MovieHistoryEventType = "unknown"
	MovieHistoryEventTypeGrabbed                MovieHistoryEventType = "grabbed"
	MovieHistoryEventTypeDownloadFolderImported MovieHistoryEventType = "downloadFolderImported"
	MovieHistoryEventTypeDownloadFailed         MovieHistoryEventType = "downloadFailed"
	MovieHistoryEventTypeMovieFileDeleted       MovieHistoryEventType = "movieFileDeleted"
	MovieHistoryEventTypeMovieFolderImported    MovieHistoryEventType = "movieFolderImported"
	MovieHistoryEventTypeMovieFileRenamed       MovieHistoryEventType = "movieFileRenamed"
	MovieHistoryEventTypeDownloadIgnored        MovieHistoryEventType = "downloadIgnored"
)

// PossibleValuesForMovieHistoryEventType returns every value of MovieHistoryEventType.
func PossibleValuesForMovieHistoryEventType() []string {
	return []string{
		string(MovieHistoryEventTypeUnknown),
		string(MovieHistoryEventTypeGrabbed),
		string(MovieHistoryEventTypeDownloadFolderImported),
		string(MovieHistoryEventTypeDownloadFailed),
		string(MovieHistoryEventTypeMovieFileDeleted),
		string(MovieHistoryEventTypeMovieFolderImported),
		string(MovieHistoryEventTypeMovieFileRenamed),
		string(MovieHistoryEventTypeDownloadIgnored),
	}
}
