// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// DeleteExclusionsBulkOperationResponse is the result of DeleteExclusionsBulk.
type DeleteExclusionsBulkOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteExclusionsBulk calls DELETE /api/v3/exclusions/bulk.
func (c Client) DeleteExclusionsBulk(ctx context.Context, input ImportListExclusionBulkResource) (result DeleteExclusionsBulkOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodDelete,
		Path:       "/api/v3/exclusions/bulk",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
