// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// ImportListExclusionResource is the "ImportListExclusionResource" schema.
type ImportListExclusionResource struct {
	ConfigContract     string                        `json:"configContract,omitempty"`
	Fields             []Field                       `json:"fields,omitzero"`
	Id                 int                           `json:"id,omitempty"`
	Implementation     string                        `json:"implementation,omitempty"`
	ImplementationName string                        `json:"implementationName,omitempty"`
	InfoLink           string                        `json:"infoLink,omitempty"`
	Message            *ProviderMessage              `json:"message,omitempty"`
	MovieTitle         string                        `json:"movieTitle,omitempty"`
	MovieYear          int                           `json:"movieYear,omitempty"`
	Name               string                        `json:"name,omitempty"`
	Presets            []ImportListExclusionResource `json:"presets,omitzero"`
	Tags               []int                         `json:"tags,omitzero"`
	TmdbId             int                           `json:"tmdbId,omitempty"`
}
