// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetConfigImportlistByIdOperationResponse is the result of GetConfigImportlistById.
type GetConfigImportlistByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *ImportListConfigResource
}

// GetConfigImportlistById calls GET /api/v3/config/importlist/{id}.
func (c Client) GetConfigImportlistById(ctx context.Context, id int) (result GetConfigImportlistByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v3/config/importlist/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model ImportListConfigResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
