// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetExclusionsOperationResponse is the result of GetExclusions.
type GetExclusionsOperationResponse struct {
	HttpResponse *http.Response
	Model        []ImportListExclusionResource
}

// GetExclusions calls GET /api/v3/exclusions.
//
// Deprecated: the document marks this operation deprecated.
func (c Client) GetExclusions(ctx context.Context) (result GetExclusionsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/exclusions",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
