// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// PostImportlistOperationResponse is the result of PostImportlist.
type PostImportlistOperationResponse struct {
	HttpResponse *http.Response
	Model        *ImportListResource
}

// PostImportlistOperationOptions holds the query and header parameters of PostImportlist.
type PostImportlistOperationOptions struct {
	ForceSave *bool
}

// ToHeaders returns the header parameters the options set.
func (o PostImportlistOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PostImportlistOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.ForceSave != nil {
		out.Append("forceSave", strconv.FormatBool(*o.ForceSave))
	}
	return &out
}

// PostImportlist calls POST /api/v3/importlist.
func (c Client) PostImportlist(ctx context.Context, input ImportListResource, options PostImportlistOperationOptions) (result PostImportlistOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusCreated,
		},
		HttpMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          "/api/v3/importlist",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model ImportListResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
