// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetExclusionsPagedOperationResponse is the result of GetExclusionsPaged.
type GetExclusionsPagedOperationResponse struct {
	HttpResponse *http.Response
	Model        *ImportListExclusionResourcePagingResource
}

// GetExclusionsPagedOperationOptions holds the query and header parameters of GetExclusionsPaged.
type GetExclusionsPagedOperationOptions struct {
	Page          int
	PageSize      int
	SortKey       string
	SortDirection SortDirection
}

// ToHeaders returns the header parameters the options set.
func (o GetExclusionsPagedOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetExclusionsPagedOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Page != 0 {
		out.Append("page", strconv.Itoa(o.Page))
	}
	if o.PageSize != 0 {
		out.Append("pageSize", strconv.Itoa(o.PageSize))
	}
	if o.SortKey != "" {
		out.Append("sortKey", o.SortKey)
	}
	if o.SortDirection != "" {
		out.Append("sortDirection", string(o.SortDirection))
	}
	return &out
}

// GetExclusionsPaged calls GET /api/v3/exclusions/paged.
func (c Client) GetExclusionsPaged(ctx context.Context, options GetExclusionsPagedOperationOptions) (result GetExclusionsPagedOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/exclusions/paged",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model ImportListExclusionResourcePagingResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}

// GetExclusionsPagedCompleteResult is every result GetExclusionsPagedComplete loaded.
type GetExclusionsPagedCompleteResult struct {
	LatestHttpResponse *http.Response
	Items              []ImportListExclusionResource
}

// GetExclusionsPagedComplete calls GetExclusionsPaged page by page from options.Page (the first
// when unset) until every result is loaded. options.PageSize is the page size,
// client.DefaultPageSize when unset.
func (c Client) GetExclusionsPagedComplete(ctx context.Context, options GetExclusionsPagedOperationOptions) (result GetExclusionsPagedCompleteResult, err error) {
	if options.PageSize <= 0 {
		options.PageSize = client.DefaultPageSize
	}
	if options.Page <= 0 {
		options.Page = 1
	}
	for {
		var page GetExclusionsPagedOperationResponse
		page, err = c.GetExclusionsPaged(ctx, options)
		result.LatestHttpResponse = page.HttpResponse
		if err != nil {
			err = fmt.Errorf("loading results: %w", err)
			return
		}
		if page.Model == nil || len(page.Model.Records) == 0 {
			return
		}
		result.Items = append(result.Items, page.Model.Records...)
		// a short page is the last; so is reaching the total the server reports
		if len(page.Model.Records) < options.PageSize || page.Model.TotalRecords > 0 && len(result.Items) >= page.Model.TotalRecords {
			return
		}
		options.Page++
	}
}
