// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetExclusionsByIdOperationResponse is the result of GetExclusionsById.
type GetExclusionsByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *ImportListExclusionResource
}

// GetExclusionsById calls GET /api/v3/exclusions/{id}.
func (c Client) GetExclusionsById(ctx context.Context, id int) (result GetExclusionsByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v3/exclusions/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model ImportListExclusionResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
