// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// ImportListResource is the "ImportListResource" schema.
type ImportListResource struct {
	ConfigContract      string               `json:"configContract,omitempty"`
	EnableAuto          *bool                `json:"enableAuto,omitempty"`
	Enabled             *bool                `json:"enabled,omitempty"`
	Fields              []Field              `json:"fields,omitzero"`
	Id                  int                  `json:"id,omitempty"`
	Implementation      string               `json:"implementation,omitempty"`
	ImplementationName  string               `json:"implementationName,omitempty"`
	InfoLink            string               `json:"infoLink,omitempty"`
	ListOrder           int                  `json:"listOrder,omitempty"`
	ListType            ImportListType       `json:"listType,omitempty"`
	Message             *ProviderMessage     `json:"message,omitempty"`
	MinRefreshInterval  string               `json:"minRefreshInterval,omitempty"`
	MinimumAvailability MovieStatusType      `json:"minimumAvailability,omitempty"`
	Monitor             MonitorTypes         `json:"monitor,omitempty"`
	Name                string               `json:"name,omitempty"`
	Presets             []ImportListResource `json:"presets,omitzero"`
	QualityProfileId    int                  `json:"qualityProfileId,omitempty"`
	RootFolderPath      string               `json:"rootFolderPath,omitempty"`
	SearchOnAdd         *bool                `json:"searchOnAdd,omitempty"`
	Tags                []int                `json:"tags,omitzero"`
}
