// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// PostImportlistMovieOperationResponse is the result of PostImportlistMovie.
type PostImportlistMovieOperationResponse struct {
	HttpResponse *http.Response
	Model        []MovieResource
}

// PostImportlistMovie calls POST /api/v3/importlist/movie.
func (c Client) PostImportlistMovie(ctx context.Context, input []MovieResource) (result PostImportlistMovieOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodPost,
		Path:       "/api/v3/importlist/movie",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
