// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"encoding/json"
	"net/http"
	"strconv"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetImportlistMovieOperationResponse is the result of GetImportlistMovie.
type GetImportlistMovieOperationResponse struct {
	HttpResponse *http.Response
	Model        json.RawMessage
}

// GetImportlistMovieOperationOptions holds the query and header parameters of GetImportlistMovie.
type GetImportlistMovieOperationOptions struct {
	IncludeRecommendations *bool
	IncludeTrending        *bool
	IncludePopular         *bool
}

// ToHeaders returns the header parameters the options set.
func (o GetImportlistMovieOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetImportlistMovieOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.IncludeRecommendations != nil {
		out.Append("includeRecommendations", strconv.FormatBool(*o.IncludeRecommendations))
	}
	if o.IncludeTrending != nil {
		out.Append("includeTrending", strconv.FormatBool(*o.IncludeTrending))
	}
	if o.IncludePopular != nil {
		out.Append("includePopular", strconv.FormatBool(*o.IncludePopular))
	}
	return &out
}

// GetImportlistMovie calls GET /api/v3/importlist/movie.
func (c Client) GetImportlistMovie(ctx context.Context, options GetImportlistMovieOperationOptions) (result GetImportlistMovieOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/importlist/movie",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
