// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// ImportListConfigResource is the "ImportListConfigResource" schema.
type ImportListConfigResource struct {
	Id            int    `json:"id,omitempty"`
	ListSyncLevel string `json:"listSyncLevel,omitempty"`
}
