// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// PostImportlistTestallOperationResponse is the result of PostImportlistTestall.
type PostImportlistTestallOperationResponse struct {
	HttpResponse *http.Response
	Model        []ProviderTestAllResult
}

// PostImportlistTestall calls POST /api/v3/importlist/testall.
func (c Client) PostImportlistTestall(ctx context.Context) (result PostImportlistTestallOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodPost,
		Path:       "/api/v3/importlist/testall",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
