// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetImportlistSchemaOperationResponse is the result of GetImportlistSchema.
type GetImportlistSchemaOperationResponse struct {
	HttpResponse *http.Response
	Model        []ImportListResource
}

// GetImportlistSchema calls GET /api/v3/importlist/schema.
func (c Client) GetImportlistSchema(ctx context.Context) (result GetImportlistSchemaOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/importlist/schema",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
