// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// ImportListBulkResource is the "ImportListBulkResource" schema.
type ImportListBulkResource struct {
	ApplyTags           ApplyTags       `json:"applyTags,omitempty"`
	EnableAuto          *bool           `json:"enableAuto,omitempty"`
	Enabled             *bool           `json:"enabled,omitempty"`
	Ids                 []int           `json:"ids,omitzero"`
	MinimumAvailability MovieStatusType `json:"minimumAvailability,omitempty"`
	QualityProfileId    *int            `json:"qualityProfileId,omitempty"`
	RootFolderPath      string          `json:"rootFolderPath,omitempty"`
	Tags                []int           `json:"tags,omitzero"`
}
