// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// PostExclusionsBulkOperationResponse is the result of PostExclusionsBulk.
type PostExclusionsBulkOperationResponse struct {
	HttpResponse *http.Response
	Model        []ImportListExclusionResource
}

// PostExclusionsBulk calls POST /api/v3/exclusions/bulk.
func (c Client) PostExclusionsBulk(ctx context.Context, input []ImportListExclusionResource) (result PostExclusionsBulkOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodPost,
		Path:       "/api/v3/exclusions/bulk",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
