// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// PostImportlistTestOperationResponse is the result of PostImportlistTest.
type PostImportlistTestOperationResponse struct {
	HttpResponse *http.Response
}

// PostImportlistTestOperationOptions holds the query and header parameters of PostImportlistTest.
type PostImportlistTestOperationOptions struct {
	ForceTest *bool
}

// ToHeaders returns the header parameters the options set.
func (o PostImportlistTestOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PostImportlistTestOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.ForceTest != nil {
		out.Append("forceTest", strconv.FormatBool(*o.ForceTest))
	}
	return &out
}

// PostImportlistTest calls POST /api/v3/importlist/test.
func (c Client) PostImportlistTest(ctx context.Context, input ImportListResource, options PostImportlistTestOperationOptions) (result PostImportlistTestOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodPost,
		OptionsObject: options,
		Path:          "/api/v3/importlist/test",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
