// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// PostIndexerTestallOperationResponse is the result of PostIndexerTestall.
type PostIndexerTestallOperationResponse struct {
	HttpResponse *http.Response
	Model        []ProviderTestAllResult
}

// PostIndexerTestall calls POST /api/v3/indexer/testall.
func (c Client) PostIndexerTestall(ctx context.Context) (result PostIndexerTestallOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodPost,
		Path:       "/api/v3/indexer/testall",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
