// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// IndexerConfigResource is the "IndexerConfigResource" schema.
type IndexerConfigResource struct {
	AllowHardcodedSubs       *bool  `json:"allowHardcodedSubs,omitempty"`
	AvailabilityDelay        int    `json:"availabilityDelay,omitempty"`
	Id                       int    `json:"id,omitempty"`
	MaximumSize              int    `json:"maximumSize,omitempty"`
	MinimumAge               int    `json:"minimumAge,omitempty"`
	PreferIndexerFlags       *bool  `json:"preferIndexerFlags,omitempty"`
	Retention                int    `json:"retention,omitempty"`
	RssSyncInterval          int    `json:"rssSyncInterval,omitempty"`
	WhitelistedHardcodedSubs string `json:"whitelistedHardcodedSubs,omitempty"`
}
