// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetIndexerflagOperationResponse is the result of GetIndexerflag.
type GetIndexerflagOperationResponse struct {
	HttpResponse *http.Response
	Model        []IndexerFlagResource
}

// GetIndexerflag calls GET /api/v3/indexerflag.
func (c Client) GetIndexerflag(ctx context.Context) (result GetIndexerflagOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/indexerflag",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
