// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetManualimportOperationResponse is the result of GetManualimport.
type GetManualimportOperationResponse struct {
	HttpResponse *http.Response
	Model        []ManualImportResource
}

// GetManualimportOperationOptions holds the query and header parameters of GetManualimport.
type GetManualimportOperationOptions struct {
	Folder              string
	DownloadId          string
	MovieId             int
	FilterExistingFiles *bool
}

// ToHeaders returns the header parameters the options set.
func (o GetManualimportOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetManualimportOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Folder != "" {
		out.Append("folder", o.Folder)
	}
	if o.DownloadId != "" {
		out.Append("downloadId", o.DownloadId)
	}
	if o.MovieId != 0 {
		out.Append("movieId", strconv.Itoa(o.MovieId))
	}
	if o.FilterExistingFiles != nil {
		out.Append("filterExistingFiles", strconv.FormatBool(*o.FilterExistingFiles))
	}
	return &out
}

// GetManualimport calls GET /api/v3/manualimport.
func (c Client) GetManualimport(ctx context.Context, options GetManualimportOperationOptions) (result GetManualimportOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/manualimport",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
