// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// ManualImportReprocessResource is the "ManualImportReprocessResource" schema.
type ManualImportReprocessResource struct {
	CustomFormatScore int                       `json:"customFormatScore,omitempty"`
	CustomFormats     []CustomFormatResource    `json:"customFormats,omitzero"`
	DownloadId        string                    `json:"downloadId,omitempty"`
	Id                int                       `json:"id,omitempty"`
	IndexerFlags      int                       `json:"indexerFlags,omitempty"`
	Languages         []Language                `json:"languages,omitzero"`
	Movie             *MovieResource            `json:"movie,omitempty"`
	MovieId           int                       `json:"movieId,omitempty"`
	Path              string                    `json:"path,omitempty"`
	Quality           *QualityModel             `json:"quality,omitempty"`
	Rejections        []ImportRejectionResource `json:"rejections,omitzero"`
	ReleaseGroup      string                    `json:"releaseGroup,omitempty"`
}
