// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// MediaManagementConfigResource is the "MediaManagementConfigResource" schema.
type MediaManagementConfigResource struct {
	AutoRenameFolders                       *bool                  `json:"autoRenameFolders,omitempty"`
	AutoUnmonitorPreviouslyDownloadedMovies *bool                  `json:"autoUnmonitorPreviouslyDownloadedMovies,omitempty"`
	ChmodFolder                             string                 `json:"chmodFolder,omitempty"`
	ChownGroup                              string                 `json:"chownGroup,omitempty"`
	CopyUsingHardlinks                      *bool                  `json:"copyUsingHardlinks,omitempty"`
	CreateEmptyMovieFolders                 *bool                  `json:"createEmptyMovieFolders,omitempty"`
	DeleteEmptyFolders                      *bool                  `json:"deleteEmptyFolders,omitempty"`
	DownloadPropersAndRepacks               ProperDownloadTypes    `json:"downloadPropersAndRepacks,omitempty"`
	EnableMediaInfo                         *bool                  `json:"enableMediaInfo,omitempty"`
	ExtraFileExtensions                     string                 `json:"extraFileExtensions,omitempty"`
	FileDate                                FileDateType           `json:"fileDate,omitempty"`
	Id                                      int                    `json:"id,omitempty"`
	ImportExtraFiles                        *bool                  `json:"importExtraFiles,omitempty"`
	MinimumFreeSpaceWhenImporting           int                    `json:"minimumFreeSpaceWhenImporting,omitempty"`
	PathsDefaultStatic                      *bool                  `json:"pathsDefaultStatic,omitempty"`
	RecycleBin                              string                 `json:"recycleBin,omitempty"`
	RecycleBinCleanupDays                   int                    `json:"recycleBinCleanupDays,omitempty"`
	RescanAfterRefresh                      RescanAfterRefreshType `json:"rescanAfterRefresh,omitempty"`
	ScriptImportPath                        string                 `json:"scriptImportPath,omitempty"`
	SetPermissionsLinux                     *bool                  `json:"setPermissionsLinux,omitempty"`
	SkipFreeSpaceCheckWhenImporting         *bool                  `json:"skipFreeSpaceCheckWhenImporting,omitempty"`
	UseScriptImport                         *bool                  `json:"useScriptImport,omitempty"`
}
