// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetMediacoverByMovieIdByFilenameOperationResponse is the result of GetMediacoverByMovieIdByFilename.
//
// The operation answers image/*, left unread in HttpResponse.Body, which
// the caller must close.
type GetMediacoverByMovieIdByFilenameOperationResponse struct {
	HttpResponse *http.Response
}

// GetMediacoverByMovieIdByFilename calls GET /api/v3/mediacover/{movieId}/{filename}.
func (c Client) GetMediacoverByMovieIdByFilename(ctx context.Context, movieId int, filename string) (result GetMediacoverByMovieIdByFilenameOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:     http.MethodGet,
		Path:           fmt.Sprintf("/api/v3/mediacover/%d/%s", movieId, url.PathEscape(filename)),
		StreamResponse: true,
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
