// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// FileDateType is the "FileDateType" enum.
type FileDateType string

// Values of FileDateType.
const (
	FileDateTypeNone    FileDateType = "none"
	FileDateTypeCinemas FileDateType = "cinemas"
	FileDateTypeRelease FileDateType = "release"
)

// PossibleValuesForFileDateType returns every value of FileDateType.
func PossibleValuesForFileDateType() []string {
	return []string{
		string(FileDateTypeNone),
		string(FileDateTypeCinemas),
		string(FileDateTypeRelease),
	}
}

// ProperDownloadTypes is the "ProperDownloadTypes" enum.
type ProperDownloadTypes string

// Values of ProperDownloadTypes.
const (
	ProperDownloadTypesPreferAndUpgrade ProperDownloadTypes = "preferAndUpgrade"
	ProperDownloadTypesDoNotUpgrade     ProperDownloadTypes = "doNotUpgrade"
	ProperDownloadTypesDoNotPrefer      ProperDownloadTypes = "doNotPrefer"
)

// PossibleValuesForProperDownloadTypes returns every value of ProperDownloadTypes.
func PossibleValuesForProperDownloadTypes() []string {
	return []string{
		string(ProperDownloadTypesPreferAndUpgrade),
		string(ProperDownloadTypesDoNotUpgrade),
		string(ProperDownloadTypesDoNotPrefer),
	}
}

// RescanAfterRefreshType is the "RescanAfterRefreshType" enum.
type RescanAfterRefreshType string

// Values of RescanAfterRefreshType.
const (
	RescanAfterRefreshTypeAlways      RescanAfterRefreshType = "always"
	RescanAfterRefreshTypeAfterManual RescanAfterRefreshType = "afterManual"
	RescanAfterRefreshTypeNever       RescanAfterRefreshType = "never"
)

// PossibleValuesForRescanAfterRefreshType returns every value of RescanAfterRefreshType.
func PossibleValuesForRescanAfterRefreshType() []string {
	return []string{
		string(RescanAfterRefreshTypeAlways),
		string(RescanAfterRefreshTypeAfterManual),
		string(RescanAfterRefreshTypeNever),
	}
}
