// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetConfigMediamanagementOperationResponse is the result of GetConfigMediamanagement.
type GetConfigMediamanagementOperationResponse struct {
	HttpResponse *http.Response
	Model        *MediaManagementConfigResource
}

// GetConfigMediamanagement calls GET /api/v3/config/mediamanagement.
func (c Client) GetConfigMediamanagement(ctx context.Context) (result GetConfigMediamanagementOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/config/mediamanagement",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model MediaManagementConfigResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
