// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// MetadataConfigResource is the "MetadataConfigResource" schema.
type MetadataConfigResource struct {
	CertificationCountry TMDbCountryCode `json:"certificationCountry,omitempty"`
	Id                   int             `json:"id,omitempty"`
}
