// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetConfigMetadataOperationResponse is the result of GetConfigMetadata.
type GetConfigMetadataOperationResponse struct {
	HttpResponse *http.Response
	Model        *MetadataConfigResource
}

// GetConfigMetadata calls GET /api/v3/config/metadata.
func (c Client) GetConfigMetadata(ctx context.Context) (result GetConfigMetadataOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/config/metadata",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model MetadataConfigResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
