// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// TMDbCountryCode is the "TMDbCountryCode" enum.
type TMDbCountryCode string

// Values of TMDbCountryCode.
const (
	TMDbCountryCodeAu TMDbCountryCode = "au"
	TMDbCountryCodeBr TMDbCountryCode = "br"
	TMDbCountryCodeCa TMDbCountryCode = "ca"
	TMDbCountryCodeFr TMDbCountryCode = "fr"
	TMDbCountryCodeDe TMDbCountryCode = "de"
	TMDbCountryCodeGb TMDbCountryCode = "gb"
	TMDbCountryCodeIn TMDbCountryCode = "in"
	TMDbCountryCodeIe TMDbCountryCode = "ie"
	TMDbCountryCodeIt TMDbCountryCode = "it"
	TMDbCountryCodeNz TMDbCountryCode = "nz"
	TMDbCountryCodeRo TMDbCountryCode = "ro"
	TMDbCountryCodeEs TMDbCountryCode = "es"
	TMDbCountryCodeUs TMDbCountryCode = "us"
)

// PossibleValuesForTMDbCountryCode returns every value of TMDbCountryCode.
func PossibleValuesForTMDbCountryCode() []string {
	return []string{
		string(TMDbCountryCodeAu),
		string(TMDbCountryCodeBr),
		string(TMDbCountryCodeCa),
		string(TMDbCountryCodeFr),
		string(TMDbCountryCodeDe),
		string(TMDbCountryCodeGb),
		string(TMDbCountryCodeIn),
		string(TMDbCountryCodeIe),
		string(TMDbCountryCodeIt),
		string(TMDbCountryCodeNz),
		string(TMDbCountryCodeRo),
		string(TMDbCountryCodeEs),
		string(TMDbCountryCodeUs),
	}
}
