// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetMovieOperationResponse is the result of GetMovie.
type GetMovieOperationResponse struct {
	HttpResponse *http.Response
	Model        []MovieResource
}

// GetMovieOperationOptions holds the query and header parameters of GetMovie.
type GetMovieOperationOptions struct {
	TmdbId             int
	ExcludeLocalCovers *bool
	LanguageId         int
}

// ToHeaders returns the header parameters the options set.
func (o GetMovieOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetMovieOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.TmdbId != 0 {
		out.Append("tmdbId", strconv.Itoa(o.TmdbId))
	}
	if o.ExcludeLocalCovers != nil {
		out.Append("excludeLocalCovers", strconv.FormatBool(*o.ExcludeLocalCovers))
	}
	if o.LanguageId != 0 {
		out.Append("languageId", strconv.Itoa(o.LanguageId))
	}
	return &out
}

// GetMovie calls GET /api/v3/movie.
func (c Client) GetMovie(ctx context.Context, options GetMovieOperationOptions) (result GetMovieOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/movie",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
