// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetMovieLookupImdbOperationResponse is the result of GetMovieLookupImdb.
type GetMovieLookupImdbOperationResponse struct {
	HttpResponse *http.Response
	Model        *MovieResource
}

// GetMovieLookupImdbOperationOptions holds the query and header parameters of GetMovieLookupImdb.
type GetMovieLookupImdbOperationOptions struct {
	ImdbId string
}

// ToHeaders returns the header parameters the options set.
func (o GetMovieLookupImdbOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetMovieLookupImdbOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.ImdbId != "" {
		out.Append("imdbId", o.ImdbId)
	}
	return &out
}

// GetMovieLookupImdb calls GET /api/v3/movie/lookup/imdb.
func (c Client) GetMovieLookupImdb(ctx context.Context, options GetMovieLookupImdbOperationOptions) (result GetMovieLookupImdbOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/movie/lookup/imdb",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model MovieResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
