// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetMovieLookupTmdbOperationResponse is the result of GetMovieLookupTmdb.
type GetMovieLookupTmdbOperationResponse struct {
	HttpResponse *http.Response
	Model        *MovieResource
}

// GetMovieLookupTmdbOperationOptions holds the query and header parameters of GetMovieLookupTmdb.
type GetMovieLookupTmdbOperationOptions struct {
	TmdbId int
}

// ToHeaders returns the header parameters the options set.
func (o GetMovieLookupTmdbOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetMovieLookupTmdbOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.TmdbId != 0 {
		out.Append("tmdbId", strconv.Itoa(o.TmdbId))
	}
	return &out
}

// GetMovieLookupTmdb calls GET /api/v3/movie/lookup/tmdb.
func (c Client) GetMovieLookupTmdb(ctx context.Context, options GetMovieLookupTmdbOperationOptions) (result GetMovieLookupTmdbOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/movie/lookup/tmdb",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model MovieResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
