// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetMovieLookupOperationResponse is the result of GetMovieLookup.
type GetMovieLookupOperationResponse struct {
	HttpResponse *http.Response
	Model        []MovieResource
}

// GetMovieLookupOperationOptions holds the query and header parameters of GetMovieLookup.
type GetMovieLookupOperationOptions struct {
	Term string
}

// ToHeaders returns the header parameters the options set.
func (o GetMovieLookupOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetMovieLookupOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.Term != "" {
		out.Append("term", o.Term)
	}
	return &out
}

// GetMovieLookup calls GET /api/v3/movie/lookup.
func (c Client) GetMovieLookup(ctx context.Context, options GetMovieLookupOperationOptions) (result GetMovieLookupOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/movie/lookup",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
