// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// DeleteMovieEditorOperationResponse is the result of DeleteMovieEditor.
type DeleteMovieEditorOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteMovieEditor calls DELETE /api/v3/movie/editor.
func (c Client) DeleteMovieEditor(ctx context.Context, input MovieEditorResource) (result DeleteMovieEditorOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodDelete,
		Path:       "/api/v3/movie/editor",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
