// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// PutMovieByIdOperationResponse is the result of PutMovieById.
type PutMovieByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *MovieResource
}

// PutMovieByIdOperationOptions holds the query and header parameters of PutMovieById.
type PutMovieByIdOperationOptions struct {
	MoveFiles *bool
}

// ToHeaders returns the header parameters the options set.
func (o PutMovieByIdOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o PutMovieByIdOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.MoveFiles != nil {
		out.Append("moveFiles", strconv.FormatBool(*o.MoveFiles))
	}
	return &out
}

// PutMovieById calls PUT /api/v3/movie/{id}.
func (c Client) PutMovieById(ctx context.Context, id int, input MovieResource, options PutMovieByIdOperationOptions) (result PutMovieByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusAccepted,
		},
		HttpMethod:    http.MethodPut,
		OptionsObject: options,
		Path:          fmt.Sprintf("/api/v3/movie/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model MovieResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
