// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// PutMoviefileEditorOperationResponse is the result of PutMoviefileEditor.
type PutMoviefileEditorOperationResponse struct {
	HttpResponse *http.Response
	Model        []MovieFileResource
}

// PutMoviefileEditor calls PUT /api/v3/moviefile/editor.
//
// Deprecated: the document marks this operation deprecated.
func (c Client) PutMoviefileEditor(ctx context.Context, input MovieFileListResource) (result PutMoviefileEditorOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusAccepted,
		},
		HttpMethod: http.MethodPut,
		Path:       "/api/v3/moviefile/editor",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
