// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetMovieByIdFolderOperationResponse is the result of GetMovieByIdFolder.
type GetMovieByIdFolderOperationResponse struct {
	HttpResponse *http.Response
	Model        json.RawMessage
}

// GetMovieByIdFolder calls GET /api/v3/movie/{id}/folder.
func (c Client) GetMovieByIdFolder(ctx context.Context, id int) (result GetMovieByIdFolderOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v3/movie/%d/folder", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
