// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"fmt"
	"net/http"
	"strconv"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// DeleteMovieByIdOperationResponse is the result of DeleteMovieById.
type DeleteMovieByIdOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteMovieByIdOperationOptions holds the query and header parameters of DeleteMovieById.
type DeleteMovieByIdOperationOptions struct {
	DeleteFiles        *bool
	AddImportExclusion *bool
}

// ToHeaders returns the header parameters the options set.
func (o DeleteMovieByIdOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o DeleteMovieByIdOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.DeleteFiles != nil {
		out.Append("deleteFiles", strconv.FormatBool(*o.DeleteFiles))
	}
	if o.AddImportExclusion != nil {
		out.Append("addImportExclusion", strconv.FormatBool(*o.AddImportExclusion))
	}
	return &out
}

// DeleteMovieById calls DELETE /api/v3/movie/{id}.
func (c Client) DeleteMovieById(ctx context.Context, id int, options DeleteMovieByIdOperationOptions) (result DeleteMovieByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodDelete,
		OptionsObject: options,
		Path:          fmt.Sprintf("/api/v3/movie/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
