// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// DeleteMoviefileBulkOperationResponse is the result of DeleteMoviefileBulk.
type DeleteMoviefileBulkOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteMoviefileBulk calls DELETE /api/v3/moviefile/bulk.
func (c Client) DeleteMoviefileBulk(ctx context.Context, input MovieFileListResource) (result DeleteMoviefileBulkOperationResponse, err error) {
	opts := client.RequestOptions{
		ContentType: "application/json",
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodDelete,
		Path:       "/api/v3/moviefile/bulk",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	if err = req.Marshal(input); err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
