// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetMoviefileByIdOperationResponse is the result of GetMoviefileById.
type GetMoviefileByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *MovieFileResource
}

// GetMoviefileById calls GET /api/v3/moviefile/{id}.
func (c Client) GetMoviefileById(ctx context.Context, id int) (result GetMoviefileByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v3/moviefile/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model MovieFileResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
