// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// MovieEditorResource is the "MovieEditorResource" schema.
type MovieEditorResource struct {
	AddImportExclusion  *bool           `json:"addImportExclusion,omitempty"`
	ApplyTags           ApplyTags       `json:"applyTags,omitempty"`
	DeleteFiles         *bool           `json:"deleteFiles,omitempty"`
	MinimumAvailability MovieStatusType `json:"minimumAvailability,omitempty"`
	Monitored           *bool           `json:"monitored,omitempty"`
	MoveFiles           *bool           `json:"moveFiles,omitempty"`
	MovieIds            []int           `json:"movieIds,omitzero"`
	QualityProfileId    *int            `json:"qualityProfileId,omitempty"`
	RootFolderPath      string          `json:"rootFolderPath,omitempty"`
	Tags                []int           `json:"tags,omitzero"`
}
