// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetMoviefileOperationResponse is the result of GetMoviefile.
type GetMoviefileOperationResponse struct {
	HttpResponse *http.Response
	Model        []MovieFileResource
}

// GetMoviefileOperationOptions holds the query and header parameters of GetMoviefile.
type GetMoviefileOperationOptions struct {
	MovieId      []int
	MovieFileIds []int
}

// ToHeaders returns the header parameters the options set.
func (o GetMoviefileOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetMoviefileOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	for _, v := range o.MovieId {
		out.Append("movieId", strconv.Itoa(v))
	}
	for _, v := range o.MovieFileIds {
		out.Append("movieFileIds", strconv.Itoa(v))
	}
	return &out
}

// GetMoviefile calls GET /api/v3/moviefile.
func (c Client) GetMoviefile(ctx context.Context, options GetMoviefileOperationOptions) (result GetMoviefileOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/moviefile",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
