// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// ColonReplacementFormat is the "ColonReplacementFormat" enum.
type ColonReplacementFormat string

// Values of ColonReplacementFormat.
const (
	ColonReplacementFormatDelete         ColonReplacementFormat = "delete"
	ColonReplacementFormatDash           ColonReplacementFormat = "dash"
	ColonReplacementFormatSpaceDash      ColonReplacementFormat = "spaceDash"
	ColonReplacementFormatSpaceDashSpace ColonReplacementFormat = "spaceDashSpace"
	ColonReplacementFormatSmart          ColonReplacementFormat = "smart"
)

// PossibleValuesForColonReplacementFormat returns every value of ColonReplacementFormat.
func PossibleValuesForColonReplacementFormat() []string {
	return []string{
		string(ColonReplacementFormatDelete),
		string(ColonReplacementFormatDash),
		string(ColonReplacementFormatSpaceDash),
		string(ColonReplacementFormatSpaceDashSpace),
		string(ColonReplacementFormatSmart),
	}
}
