// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// NamingConfigResource is the "NamingConfigResource" schema.
type NamingConfigResource struct {
	ColonReplacementFormat   ColonReplacementFormat `json:"colonReplacementFormat,omitempty"`
	Id                       int                    `json:"id,omitempty"`
	MovieFolderFormat        string                 `json:"movieFolderFormat,omitempty"`
	RenameMovies             *bool                  `json:"renameMovies,omitempty"`
	ReplaceIllegalCharacters *bool                  `json:"replaceIllegalCharacters,omitempty"`
	StandardMovieFormat      string                 `json:"standardMovieFormat,omitempty"`
}
