// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"net/http"
	"testing"

	"github.com/katbyte/radarr-mcp/lib/client"
)

func TestOperationGetConfigNamingExamples(t *testing.T) {
	t.Parallel()

	c, s := newOperationServer(t, 200, "application/json", "{}")
	result, err := c.GetConfigNamingExamples(t.Context(), GetConfigNamingExamplesOperationOptions{
		RenameMovies:             new(true),
		ReplaceIllegalCharacters: new(true),
		ColonReplacementFormat:   ColonReplacementFormatDelete,
		StandardMovieFormat:      "v-StandardMovieFormat",
		MovieFolderFormat:        "v-MovieFolderFormat",
		Id:                       7,
		ResourceName:             "v-ResourceName",
	})
	if err != nil {
		t.Fatal(err)
	}
	r, body := s.only(t)
	_ = body
	expectRequest(t, r, http.MethodGet, "/api/v3/config/naming/examples")
	expectQuery(t, r, "renameMovies", "true")
	expectQuery(t, r, "replaceIllegalCharacters", "true")
	expectQuery(t, r, "colonReplacementFormat", "delete")
	expectQuery(t, r, "standardMovieFormat", "v-StandardMovieFormat")
	expectQuery(t, r, "movieFolderFormat", "v-MovieFolderFormat")
	expectQuery(t, r, "id", "7")
	expectQuery(t, r, "resourceName", "v-ResourceName")
	if result.HttpResponse == nil || result.HttpResponse.StatusCode != 200 {
		t.Fatalf("HttpResponse = %+v", result.HttpResponse)
	}
	if result.Model == nil {
		t.Error("the model was not decoded")
	}

	// an answer that does not decode is an error, with the response
	c, _ = newOperationServer(t, 200, "application/json", "<html>")
	result, err = c.GetConfigNamingExamples(t.Context(), GetConfigNamingExamplesOperationOptions{
		RenameMovies:             new(true),
		ReplaceIllegalCharacters: new(true),
		ColonReplacementFormat:   ColonReplacementFormatDelete,
		StandardMovieFormat:      "v-StandardMovieFormat",
		MovieFolderFormat:        "v-MovieFolderFormat",
		Id:                       7,
		ResourceName:             "v-ResourceName",
	})
	if err == nil || client.StatusCode(err) != 0 || result.HttpResponse == nil {
		t.Errorf("an answer that does not decode = %v", err)
	}

	// a status the operation does not document is an error, with the response
	c, _ = newOperationServer(t, 418, "text/plain", "no")
	result, err = c.GetConfigNamingExamples(t.Context(), GetConfigNamingExamplesOperationOptions{
		RenameMovies:             new(true),
		ReplaceIllegalCharacters: new(true),
		ColonReplacementFormat:   ColonReplacementFormatDelete,
		StandardMovieFormat:      "v-StandardMovieFormat",
		MovieFolderFormat:        "v-MovieFolderFormat",
		Id:                       7,
		ResourceName:             "v-ResourceName",
	})
	if client.StatusCode(err) != 418 || result.HttpResponse == nil {
		t.Errorf("an undocumented status = %v, %+v", err, result.HttpResponse)
	}
}
