// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"encoding/json"
	"net/http"
	"strconv"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetConfigNamingExamplesOperationResponse is the result of GetConfigNamingExamples.
type GetConfigNamingExamplesOperationResponse struct {
	HttpResponse *http.Response
	Model        json.RawMessage
}

// GetConfigNamingExamplesOperationOptions holds the query and header parameters of GetConfigNamingExamples.
type GetConfigNamingExamplesOperationOptions struct {
	RenameMovies             *bool
	ReplaceIllegalCharacters *bool
	ColonReplacementFormat   ColonReplacementFormat
	StandardMovieFormat      string
	MovieFolderFormat        string
	Id                       int
	ResourceName             string
}

// ToHeaders returns the header parameters the options set.
func (o GetConfigNamingExamplesOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetConfigNamingExamplesOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.RenameMovies != nil {
		out.Append("renameMovies", strconv.FormatBool(*o.RenameMovies))
	}
	if o.ReplaceIllegalCharacters != nil {
		out.Append("replaceIllegalCharacters", strconv.FormatBool(*o.ReplaceIllegalCharacters))
	}
	if o.ColonReplacementFormat != "" {
		out.Append("colonReplacementFormat", string(o.ColonReplacementFormat))
	}
	if o.StandardMovieFormat != "" {
		out.Append("standardMovieFormat", o.StandardMovieFormat)
	}
	if o.MovieFolderFormat != "" {
		out.Append("movieFolderFormat", o.MovieFolderFormat)
	}
	if o.Id != 0 {
		out.Append("id", strconv.Itoa(o.Id))
	}
	if o.ResourceName != "" {
		out.Append("resourceName", o.ResourceName)
	}
	return &out
}

// GetConfigNamingExamples calls GET /api/v3/config/naming/examples.
func (c Client) GetConfigNamingExamples(ctx context.Context, options GetConfigNamingExamplesOperationOptions) (result GetConfigNamingExamplesOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/config/naming/examples",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
