// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// NotificationResource is the "NotificationResource" schema.
type NotificationResource struct {
	ConfigContract                      string                 `json:"configContract,omitempty"`
	Fields                              []Field                `json:"fields,omitzero"`
	Id                                  int                    `json:"id,omitempty"`
	Implementation                      string                 `json:"implementation,omitempty"`
	ImplementationName                  string                 `json:"implementationName,omitempty"`
	IncludeHealthWarnings               *bool                  `json:"includeHealthWarnings,omitempty"`
	InfoLink                            string                 `json:"infoLink,omitempty"`
	Link                                string                 `json:"link,omitempty"`
	Message                             *ProviderMessage       `json:"message,omitempty"`
	Name                                string                 `json:"name,omitempty"`
	OnApplicationUpdate                 *bool                  `json:"onApplicationUpdate,omitempty"`
	OnDownload                          *bool                  `json:"onDownload,omitempty"`
	OnGrab                              *bool                  `json:"onGrab,omitempty"`
	OnHealthIssue                       *bool                  `json:"onHealthIssue,omitempty"`
	OnHealthRestored                    *bool                  `json:"onHealthRestored,omitempty"`
	OnManualInteractionRequired         *bool                  `json:"onManualInteractionRequired,omitempty"`
	OnMovieAdded                        *bool                  `json:"onMovieAdded,omitempty"`
	OnMovieDelete                       *bool                  `json:"onMovieDelete,omitempty"`
	OnMovieFileDelete                   *bool                  `json:"onMovieFileDelete,omitempty"`
	OnMovieFileDeleteForUpgrade         *bool                  `json:"onMovieFileDeleteForUpgrade,omitempty"`
	OnRename                            *bool                  `json:"onRename,omitempty"`
	OnUpgrade                           *bool                  `json:"onUpgrade,omitempty"`
	Presets                             []NotificationResource `json:"presets,omitzero"`
	SupportsOnApplicationUpdate         *bool                  `json:"supportsOnApplicationUpdate,omitempty"`
	SupportsOnDownload                  *bool                  `json:"supportsOnDownload,omitempty"`
	SupportsOnGrab                      *bool                  `json:"supportsOnGrab,omitempty"`
	SupportsOnHealthIssue               *bool                  `json:"supportsOnHealthIssue,omitempty"`
	SupportsOnHealthRestored            *bool                  `json:"supportsOnHealthRestored,omitempty"`
	SupportsOnManualInteractionRequired *bool                  `json:"supportsOnManualInteractionRequired,omitempty"`
	SupportsOnMovieAdded                *bool                  `json:"supportsOnMovieAdded,omitempty"`
	SupportsOnMovieDelete               *bool                  `json:"supportsOnMovieDelete,omitempty"`
	SupportsOnMovieFileDelete           *bool                  `json:"supportsOnMovieFileDelete,omitempty"`
	SupportsOnMovieFileDeleteForUpgrade *bool                  `json:"supportsOnMovieFileDeleteForUpgrade,omitempty"`
	SupportsOnRename                    *bool                  `json:"supportsOnRename,omitempty"`
	SupportsOnUpgrade                   *bool                  `json:"supportsOnUpgrade,omitempty"`
	Tags                                []int                  `json:"tags,omitzero"`
	TestCommand                         string                 `json:"testCommand,omitempty"`
}
