// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// ParseResource is the "ParseResource" schema.
type ParseResource struct {
	CustomFormatScore int                    `json:"customFormatScore,omitempty"`
	CustomFormats     []CustomFormatResource `json:"customFormats,omitzero"`
	Id                int                    `json:"id,omitempty"`
	Languages         []Language             `json:"languages,omitzero"`
	Movie             *MovieResource         `json:"movie,omitempty"`
	ParsedMovieInfo   *ParsedMovieInfo       `json:"parsedMovieInfo,omitempty"`
	Title             string                 `json:"title,omitempty"`
}
