// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// ParsedMovieInfo is the "ParsedMovieInfo" schema.
type ParsedMovieInfo struct {
	Edition            string        `json:"edition,omitempty"`
	HardcodedSubs      string        `json:"hardcodedSubs,omitempty"`
	ImdbId             string        `json:"imdbId,omitempty"`
	Languages          []Language    `json:"languages,omitzero"`
	MovieTitle         string        `json:"movieTitle,omitempty"`
	MovieTitles        []string      `json:"movieTitles,omitzero"`
	OriginalTitle      string        `json:"originalTitle,omitempty"`
	PrimaryMovieTitle  string        `json:"primaryMovieTitle,omitempty"`
	Quality            *QualityModel `json:"quality,omitempty"`
	ReleaseGroup       string        `json:"releaseGroup,omitempty"`
	ReleaseHash        string        `json:"releaseHash,omitempty"`
	ReleaseTitle       string        `json:"releaseTitle,omitempty"`
	SimpleReleaseTitle string        `json:"simpleReleaseTitle,omitempty"`
	TmdbId             int           `json:"tmdbId,omitempty"`
	Year               int           `json:"year,omitempty"`
}
