// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetQualitydefinitionOperationResponse is the result of GetQualitydefinition.
type GetQualitydefinitionOperationResponse struct {
	HttpResponse *http.Response
	Model        []QualityDefinitionResource
}

// GetQualitydefinition calls GET /api/v3/qualitydefinition.
func (c Client) GetQualitydefinition(ctx context.Context) (result GetQualitydefinitionOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/qualitydefinition",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
