// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// DeleteQualityprofileByIdOperationResponse is the result of DeleteQualityprofileById.
type DeleteQualityprofileByIdOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteQualityprofileById calls DELETE /api/v3/qualityprofile/{id}.
func (c Client) DeleteQualityprofileById(ctx context.Context, id int) (result DeleteQualityprofileByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodDelete,
		Path:       fmt.Sprintf("/api/v3/qualityprofile/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
