// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetQualityprofileOperationResponse is the result of GetQualityprofile.
type GetQualityprofileOperationResponse struct {
	HttpResponse *http.Response
	Model        []QualityProfileResource
}

// GetQualityprofile calls GET /api/v3/qualityprofile.
func (c Client) GetQualityprofile(ctx context.Context) (result GetQualityprofileOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/qualityprofile",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
