// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetQueueDetailsOperationResponse is the result of GetQueueDetails.
type GetQueueDetailsOperationResponse struct {
	HttpResponse *http.Response
	Model        []QueueResource
}

// GetQueueDetailsOperationOptions holds the query and header parameters of GetQueueDetails.
type GetQueueDetailsOperationOptions struct {
	MovieId      int
	IncludeMovie *bool
}

// ToHeaders returns the header parameters the options set.
func (o GetQueueDetailsOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetQueueDetailsOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.MovieId != 0 {
		out.Append("movieId", strconv.Itoa(o.MovieId))
	}
	if o.IncludeMovie != nil {
		out.Append("includeMovie", strconv.FormatBool(*o.IncludeMovie))
	}
	return &out
}

// GetQueueDetails calls GET /api/v3/queue/details.
func (c Client) GetQueueDetails(ctx context.Context, options GetQueueDetailsOperationOptions) (result GetQueueDetailsOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/queue/details",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
