// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"
	"strconv"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetReleaseOperationResponse is the result of GetRelease.
type GetReleaseOperationResponse struct {
	HttpResponse *http.Response
	Model        []ReleaseResource
}

// GetReleaseOperationOptions holds the query and header parameters of GetRelease.
type GetReleaseOperationOptions struct {
	MovieId int
}

// ToHeaders returns the header parameters the options set.
func (o GetReleaseOperationOptions) ToHeaders() *client.Headers {
	out := client.Headers{}
	return &out
}

// ToQuery returns the query parameters the options set.
func (o GetReleaseOperationOptions) ToQuery() *client.QueryParams {
	out := client.QueryParams{}
	if o.MovieId != 0 {
		out.Append("movieId", strconv.Itoa(o.MovieId))
	}
	return &out
}

// GetRelease calls GET /api/v3/release.
func (c Client) GetRelease(ctx context.Context, options GetReleaseOperationOptions) (result GetReleaseOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:    http.MethodGet,
		OptionsObject: options,
		Path:          "/api/v3/release",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
