// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetReleaseprofileOperationResponse is the result of GetReleaseprofile.
type GetReleaseprofileOperationResponse struct {
	HttpResponse *http.Response
	Model        []ReleaseProfileResource
}

// GetReleaseprofile calls GET /api/v3/releaseprofile.
func (c Client) GetReleaseprofile(ctx context.Context) (result GetReleaseprofileOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/releaseprofile",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
