// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetRemotepathmappingOperationResponse is the result of GetRemotepathmapping.
type GetRemotepathmappingOperationResponse struct {
	HttpResponse *http.Response
	Model        []RemotePathMappingResource
}

// GetRemotepathmapping calls GET /api/v3/remotepathmapping.
func (c Client) GetRemotepathmapping(ctx context.Context) (result GetRemotepathmappingOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       "/api/v3/remotepathmapping",
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	if err = resp.Unmarshal(&result.Model); err != nil {
		return
	}

	return
}
