// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetRemotepathmappingByIdOperationResponse is the result of GetRemotepathmappingById.
type GetRemotepathmappingByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *RemotePathMappingResource
}

// GetRemotepathmappingById calls GET /api/v3/remotepathmapping/{id}.
func (c Client) GetRemotepathmappingById(ctx context.Context, id int) (result GetRemotepathmappingByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v3/remotepathmapping/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model RemotePathMappingResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
