// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// RenameMovieResource is the "RenameMovieResource" schema.
type RenameMovieResource struct {
	ExistingPath string `json:"existingPath,omitempty"`
	Id           int    `json:"id,omitempty"`
	MovieFileId  int    `json:"movieFileId,omitempty"`
	MovieId      int    `json:"movieId,omitempty"`
	NewPath      string `json:"newPath,omitempty"`
}
