// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetRootfolderByIdOperationResponse is the result of GetRootfolderById.
type GetRootfolderByIdOperationResponse struct {
	HttpResponse *http.Response
	Model        *RootFolderResource
}

// GetRootfolderById calls GET /api/v3/rootfolder/{id}.
func (c Client) GetRootfolderById(ctx context.Context, id int) (result GetRootfolderByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodGet,
		Path:       fmt.Sprintf("/api/v3/rootfolder/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	var model RootFolderResource
	result.Model = &model
	if err = resp.Unmarshal(result.Model); err != nil {
		return
	}

	return
}
