// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"fmt"
	"net/http"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// DeleteRootfolderByIdOperationResponse is the result of DeleteRootfolderById.
type DeleteRootfolderByIdOperationResponse struct {
	HttpResponse *http.Response
}

// DeleteRootfolderById calls DELETE /api/v3/rootfolder/{id}.
func (c Client) DeleteRootfolderById(ctx context.Context, id int) (result DeleteRootfolderByIdOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod: http.MethodDelete,
		Path:       fmt.Sprintf("/api/v3/rootfolder/%d", id),
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
