// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

import (
	"context"
	"fmt"
	"net/http"
	"net/url"

	"github.com/katbyte/radarr-mcp/lib/client"
)

// GetByPathOperationResponse is the result of GetByPath.
//
// The operation answers application/octet-stream, left unread in HttpResponse.Body, which
// the caller must close.
type GetByPathOperationResponse struct {
	HttpResponse *http.Response
}

// GetByPath calls GET /{path}.
func (c Client) GetByPath(ctx context.Context, path string) (result GetByPathOperationResponse, err error) {
	opts := client.RequestOptions{
		ExpectedStatusCodes: []int{
			http.StatusOK,
		},
		HttpMethod:     http.MethodGet,
		Path:           fmt.Sprintf("/%s", url.PathEscape(path)),
		StreamResponse: true,
	}

	req, err := c.Client.NewRequest(ctx, opts)
	if err != nil {
		return
	}

	var resp *client.Response
	resp, err = req.Execute(ctx)
	if resp != nil {
		result.HttpResponse = resp.Response
	}
	if err != nil {
		return
	}

	return
}
