// Code generated by internal/pandorest; DO NOT EDIT.

package radarr

// MovieRuntimeFormatType is the "MovieRuntimeFormatType" enum.
type MovieRuntimeFormatType string

// Values of MovieRuntimeFormatType.
const (
	MovieRuntimeFormatTypeHoursMinutes MovieRuntimeFormatType = "hoursMinutes"
	MovieRuntimeFormatTypeMinutes      MovieRuntimeFormatType = "minutes"
)

// PossibleValuesForMovieRuntimeFormatType returns every value of MovieRuntimeFormatType.
func PossibleValuesForMovieRuntimeFormatType() []string {
	return []string{
		string(MovieRuntimeFormatTypeHoursMinutes),
		string(MovieRuntimeFormatTypeMinutes),
	}
}
